### ISSUE TITLE
new ThermalActor code breaks non-ITK build

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#102]
The ThermalActor code seems to use ITK functionality that is not included in our "external" copy, so for builds where `USE_ITK` is off the compilation fails.

I can think of several ways to fix this.

1. Make ITK obligatory (remove the `USE_ITK` option, since it's no longer optional).
2. Make ThermalActor optional (remove that code from source file lists in `CMakeLists.txt`) if `USE_ITK` is `OFF`
3. Adapt the ThermalActor code with some preprocessor judo to fall back to some non-ITK workaround in case `USE_ITK` is `OFF`, insert loud warnings to the user that this is not optimal and encouragements to rebuild GATE *with* ITK.
4. Some other solution.

Currently my favorite solution is number 2.

**Comment by albertine** [comment]
OK David, you're absolutely right. I have not not paid attention to that given I always build Gate with GATE_USE_ITK ON. I'll try to fix this bug (choosing your number 2 solution, my favorite one too) by the end of the day.

**Comment by dsarrut** [comment]
I tried to fix that this morning ... could you check ?

**Comment by albertine** [comment]
Thanks David, it works for me (build OK for each configuration: USE_ITK=ON and USE_ITK=OFF).
Do we keep this solution for now ?
