### ISSUE TITLE
Should GateDoseActor.cc take into account photons in dose computation ??

### ISSUE THREAD

**Issue by uhqd** [OpenGATE/Gate#104]
Hello

I come back with my remarks on GateDoseActor.cc
First thank you David to have fixed the NaN issue...
I am testing locally a version of GateDoseActor.cc that will takes into account the following. PullRequest will follow.

1. A minor issue:
The dose conversion in gray must not be done BEFORE the GateDebugMessage (with G4BestUnit)
Because G4BestUnit converts in Gray. So if the user displays debugMessage, dose is converted twice.  
I propose this order for both dose and doseToWater:
 - Dose computation
 - DebugMessage
 - dose = dose / gray
 
 
 2. More important
 If I simplify the current version of GateDoseActor.cc, it does:
 
 Part A. Dose to media
 
 	 dose = edep/density/mDoseImage.GetVoxelVolume();
 	 
 	 There is no test on the particle type here. All particles (including photons) pass this line
 
 
 Part B. Dose to water
 
 	
 	if (PartName== "proton" || PartName== "e-" || PartName== "e+" || PartName== "deuteron") 
 		doseToWater=edep/density/Volume*(DEDX_Water/1.)/(DEDX/(density*e_SI));
 	else
 		{
 		DEDX = emcalc->ComputeTotalDEDX(100, "proton", material, cut);
        DEDX_Water = emcalc->ComputeTotalDEDX(100, "proton", "G4_WATER", cut);
        doseToWater=edep/density/Volume*(DEDX_Water/1.)/(DEDX/(density*e_SI));	
 		}
 	
 	Loic GREVILLOT told me that this "else section" is not completely finished. But if I understand well, it is foreseen for exotic particle (not for conventional radiotherapy)
 	
 	
 	My remarks/questions: 
 	- In part B (doseToWater): why this if/else test is done only for dose to water (and not dose to media in part A)
 	- I tested it and the "else section" is used for "gamma" particles.
 	- in part A. (Dose to media) I have the same remark. Dose is computed for all particles, including gamma because no test is made
 	- Based on my old knowledge, dose is not deposited by gamma but by charged particles only. 
 	- May I understand that this case (dose is deposited by a photon) happens when photon energy is < cut ? 

Anyway I propose the following code (pull request will be done) with the following modifications
1. Conversion to Gray is AFTER debugMessage for both dose and doseToWater
2. I comment the else section of DoseToWater because no photon must be treated here
3. I add the same "if" section (if particle is e- or e+...) for dose to media for the same reason

I attach my file (with .txt extension because github does not allow .cc), pull request will be done soon .
[GateDoseActor.txt](https://github.com/OpenGATE/Gate/files/840875/GateDoseActor.txt)

**Comment by GrevillotL** [comment]
Hello,

1. I did not really understand why an error message should convert anything? are you sure?
For 2 and 3 the modif are not correct, as far as I understand:
3. If you add the if for the limited number of particles included, it means that dose will not be scored with any other particles! => my proposal, NO TOUCH if it is working! 
2. Same issue as before, if any other particles, the else give you doseto water = 0 - the previous Version was multiplying the dose to tissue by the stoppingpower Ratio of Protons at 100 MeV by default, which is also not optimal and should be corrected, but at least did not put the dose to 0.

=> the main issues to me seem to be:
a/ to understand while photon can depose dose? If it is a cut issue, maybe we should come back to a stopping power Ratio of electrons, assuming the energy lost by the photon is transfered totally to an electron.
b/ I agree that the current else considering Protons at 100 MeV must be changed, the main issue is to be able to get the DEDX for any particle type, thus making the dosetowater actor valid for any particles, which is currently not the case.

**Comment by uhqd** [comment]
1. Yes Sure. I checked. G4BestUnit converts in Gy (it means divide by 1e-12). If you do it before (dose/gray), it is done twice. @TomThePhysicist  recommands me to not modify  the computation line but to use (dose*gray) in G4bestunits
2. Finally (my last commit) I did not touch to :
 - Dose To Media computation (except debug message)
- Else section of DoseToWater (for exotic particles)
But I just add gamma to the "if" list because, if you don't then gamma are processed in the else part (for exotic particles). And doseToWater for gamma was not 0 in this else part. 

Maybe a phone call would be better. You can send me your number at: uhqd75 at gmail dot com

**Comment by uhqd** [comment]
To complete point 1. 
Here are the results : 

before 1.052158692734403e-10 Gy
after 105.2158692734402 Gy
using Thomas tips 1.052158692734403e-10 Gy

if you do this

        doseToWater=edep/density/Volume*(DEDX_Water/1.)/(DEDX/(density*e_SI));
         G4cout << "before " << G4BestUnit(doseToWater, "Dose") << Gateendl;; 
        doseToWater = doseToWater / gray;
        G4cout << "after " << G4BestUnit(doseToWater, "Dose") << Gateendl;; 
        G4cout << "using Thomas tips " << G4BestUnit(doseToWater*gray, "Dose") << Gateendl;;

**Comment by uhqd** [comment]
Finally (my last post today !) I found a simple way to obtain: dose = doseToWater  in a water phantom
In my macro:
`/gate/patient/setMaterial G4_WATER `

instead of 

`/gate/patient/setMaterial water`

**Comment by dsarrut** [comment]
See PR #122
