### ISSUE TITLE
How to use imageCT output？

### ISSUE THREAD

**Issue by kenyonzhao** [OpenGATE/Gate#105]
Hi, I'm a college student who is doing an assignment of CT simulation with Gate. I've done every steps introduced in the Gate users' guide except the final step of data processing because I have got some problems on it. My goal of processing data is to obtain an image of cross section of the phantom. I have tried 2 types of output: ASCII and ImageCT ( learning how to use ROOT from beginning is so hard for me). I need some help on both of these output types. 
1、The singles.dat in ASCII output that I obtained only contain  22 column instead of 23 introduced by users' guide. As a result, I don't understand the meaning of each column, and which column is useful if I want to reconstruct an image or do some data analysis. 
![image](https://cloud.githubusercontent.com/assets/26427089/23936940/cd9c2062-098f-11e7-99dc-44a98fc82c3c.png)
2、I've got some results of ImageCT output, but I don't know how to use them to reconstruct the cross section image. I tried to use ImageJ to open it, but didn't work. 

I really need some help! Thank you a lot!

**Comment by djboersma** [comment]
Dear @kenyonzhao , we use the github issues page to discuss bugs and development ideas. Your question is an excellent question for our users' mailing list. Here you can find information on how to sign up: http://opengatecollaboration.org/mailinglist

**Comment by kenyonzhao** [comment]
@djboersma ,Thanks for your help! I have post my question in the mailing list for 2 days, but there have no response until now. If you know how to deal with my question, could you lend me a hand? I will be deeply grateful!

**Comment by kenyonzhao** [comment]
http://lists.opengatecollaboration.org/mailman/private/gate-users/2017-March/009519.html
This is the question that I have post in the mailing list.

**Comment by djboersma** [comment]
Hi @kenyonzhao, I am a radiotherapy guy, I was hoping that an imaging expert would help you out. Sometimes people are too busy to check the mailing list, then you need to wait a few days for an answer. I can spy around in the code to see if I can clarify this issue, but that takes some time, so won't do that today.

**Comment by kenyonzhao** [comment]
@djboersma Thanks again! I will wait patiently for the response from the mailing list and try my best to figure it out as well.

**Comment by yuxiXo** [comment]
May I ask if you have solved it? I am also a student and I hope to get your guidance, thanks!
