### ISSUE TITLE
New user could any one help?

### ISSUE THREAD

**Issue by Engpharaon** [OpenGATE/Gate#119]
Dear Sirs,
Am just a new Gate user and  am using Vgate 7.2 , 
I'm trying to do the basic examples in the user guide but when I try to set a material "such as water "a fatal error message come out and the software rest any one can help?
Thanks a lot
Best regards
Eng. Pharaon

**Comment by uhqd** [comment]
please copy your macro that fails, we ll have a look

**Comment by dsarrut** [comment]
Hello, 
this is not an issue, please use the mailing list. 
David
