### ISSUE TITLE
Git documentation on opengatecollaboration website is very outdated

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#124]
http://opengatecollaboration.org/Git

The 'developper/write access' section (and many example git commands after that) advertises some old git server. We should update that with the GitHub information.

I wonder if the rest of the page also needs some cleaning/updating. No time to do that today, therefore just dumping this observation here in an "issue".

**Comment by brenthuisman** [comment]
If I may state my preference, it's to perform an import to Github's wiki and get rid of the old one. It'll make it much easier for small fixes. I also do not quite understand the versioning of the wiki according to the Gate releases: the search tends to give older versions first and it's not so easy to discover what was changed that way.

**Comment by albertine** [comment]
Cleaned and updated with the GitHub information

**Comment by mojca** [comment]
@albertine: for cloning your own repository (or fetching from it), it makes more sense to use `git://` rather than `https://`. That way you don't need to keep retyping your password (you need to enter the password for the private key at some point though).
