### ISSUE TITLE
Bug - linear interpolated spectrum - radionuclide energy spectrum

### ISSUE THREAD

**Issue by Maiksar** [OpenGATE/Gate#129]
Hi

I would like to report a Bug.
I am using Y-90 source and I change the spectrum from MIRD database.
In one part of the Y-90 beta spectrum there is two point with these values:

E(MeV) Probability
0.70000 6.274E-01
0.75000 6.292E-01
0.80000 6.292E-01
0.85000 6.276E-01

In my simulation the energy spectrum in the region between 0,75MeV and 0,80MeV, just fall down. 

With the help of other Gate-Users we found that the problem come from the interpolation between this two point (( .75000, 6.292E-01),(0.80000. 6.292E-01)). I don´t know the procedure that Gate follow to do the interpolation, but this is an error. 
When I changed slightly for example:
0.70000 6.274E-01
0.75000 6.292E-01
0.80000 6.291E-01
0.85000 6.276E-01

The error disappear. 

Now I am using  histogram spectrum instead of linear interpolated spectrum.
With histogram spectrum the error is not present.

**Comment by Supernabla** [comment]
The culprit is this part from [GateSPSEneDistribution::GenerateFromUserSpectrum()](https://github.com/OpenGATE/Gate/blob/3be1a80250935f63f6e1d02daea1642a3d8434a0/source/physics/src/GateSPSEneDistribution.cc):

```cpp
case 3:
    //Interpolated spectrum
    a=m_tab_energy[i];
    b=m_tab_energy[i+1];

    alpha=(m_tab_proba[i+1]-m_tab_proba[i])/(m_tab_energy[i+1]-m_tab_energy[i]);
    beta=m_tab_proba[i+1]-m_tab_energy[i+1]*alpha;
    gamma=(alpha/2)*(b*b-a*a)+beta*(b-a);
    my_rndm=G4UniformRand();
    X =(-beta+sqrt((alpha*a+beta)*(alpha*a+beta)+2*alpha*gamma*my_rndm))/(alpha);

    if((X-a)*(X-b)<=0) pEnergy=X;
    else pEnergy=(-beta-sqrt((alpha*a+beta)*(alpha*a+beta)+2*alpha*gamma*my_rndm))/(alpha);
    break;
```

I think in the case you describe `alpha` becomes zero, which leads to a *division-by-zero*, causing `X` and also `pEnergy` to be nonsense.

This should definitely be fixed!

**Comment by dsarrut** [comment]
Hello, 
what should be the value of X (and pEnergy) when alpha==0 ? 
Could you propose a PR to fix this issue ? 
thanks, 
David

**Comment by Supernabla** [comment]
Yeah, sorry. Complaining without fixing is annoying, I know... I'll look into it later today.
