### ISSUE TITLE
CMake Error: Files to be generated by multiple different commands

### ISSUE THREAD

**Issue by AndiH** [OpenGATE/Gate#135]
When compiling with a recent (3.7.2) CMake version, the following error is generated during configuration:

```
CMake Error: Files to be generated by multiple different commands: "…/GATE/source/build/CMakeFiles/Gate.dir/source/gpu/src/Gate_generated_GateGPUManager.cu.o.Release.cmake"
```

The error does not occur with an older CMake version, e.g. CMake 3.4.3.

I reckon the error comes from multiple inclusion of `GateGPUManager.cu` into file list variables. The file is, first, included into variable `sourcesGPU` in line 135 of `CMakeLists.txt`. But it is also included into variable `sources` in line 190 of the file. When the CMake variable `GATE_USE_GPU` is enabled, both variables are added to the CUDA executable (line 230). My guess is that the error comes from there.

This leads to another question, which is currently beyond my understanding of how Gate works: Why is `GateGPUManager.cu` included into CMake variable `sources`? This one is also used when not compiling for GPU.

(In a quick test I removed `GateGPUManager.cu` from the `sources` variable and successfully compiled Gate. I don't know, though, if the result is still correct.)

**Comment by djboersma** [comment]
This should be fixed with commit 3fe0800ead7f9a3baa820b18847597120615aaba
Thanks for the report, sorry for the slow response...
