### ISSUE TITLE
GPU tracking on CT applications

### ISSUE THREAD

**Issue by XiaodanXing** [OpenGATE/Gate#140]
Dear Gate-developers, I used GPU tracking to accelerate my CT simulation. I tried the example provided by Gate and got this output. 
 
![z](https://user-images.githubusercontent.com/30890745/29158070-2bbd5920-7ddc-11e7-850a-bcd273e0000c.jpg)

Then I decided to enlarge my field of view by changing the maxtheta of the source into 5 degs (which used to be 4 degs) , but the output was weird:
 ![z](https://user-images.githubusercontent.com/30890745/29157807-07cb438e-7ddb-11e7-9c69-82e8ff7301e4.jpg)
I don’t know whether it is a bug because same thing happens when I tried to rotate my phantom around x axis over 90 degs, the output was not correct either. 
/gate/patient/placement/setRotationAxis           1 0 0
/gate/patient/placement/setRotationAngle         90 deg
/gate/patient/placement/setTranslation          0 0 0 mm
The output is:
 ![z](https://user-images.githubusercontent.com/30890745/29157807-07cb438e-7ddb-11e7-9c69-82e8ff7301e4.jpg)
I thought there might be something wrong with the GateTransTomoActor, but I can’t figure out what it is.

**Comment by dsarrut** [comment]
Hello, 

GPU in Gate will be discontinuited. GPU Monte-Carlo will be available in GGEMS: http://www.ggems.fr

**Comment by Xiaotongzh** [comment]
I also tried to run an example of using the GPU for simulation. But I found that X-rays didn't seem to pass through the phantom, just like the picture. 
_![image](https://user-images.githubusercontent.com/39394003/40213433-00084dce-5a88-11e8-9bda-5f8fa02bc126.png)_
Have you met this situation? I don't know where the problem is.

**Comment by djboersma** [comment]
Hi @Xiaotongzh , unfortunately we do not have a GPU expert around here to answer your question. And as dsarrut indicated, the GPU will be removed from the next release (or at least strongly deprecated and no longer supported by us).
I would suggest that you contact the original authors of our GPU code, I think that they implemented this functionality in a stand-alone program program (or library, actually) called GGEMS. See: http://ggems.fr/
Good luck!

**Comment by Xiaotongzh** [comment]
Hello, djboersma, your answer is very useful to me. But after opening the link you gave me about GGEMS, I cannot find a way to download GGEMS. Do you know how to get GGEMS? Another question is whether GGEMS and GATE are two independent softwares?

**Comment by Xiaotongzh** [comment]
Hello, @djboersma , your answer is very useful to me. But after opening the link you gave me about GGEMS, I cannot find a way to download GGEMS. Do you know how to get GGEMS? Another question is whether GGEMS and GATE are two independent softwares?

**Comment by Hoonly** [comment]
It said that 'GGEMS will be released in last trimester 2017' on the webpage, but until 2020, we can not find anything about it. Could you please give more information?

**Comment by djboersma** [comment]
> 
> 
> It said that 'GGEMS will be released in last trimester 2017' on the webpage, but until 2020, we can not find anything about it. Could you please give more information?

Hi @Hoonly , I wish I could. I recommend asking the authors, there are two contact email addresses on the GGEMS web page. Note that GGEMS is not part of GATE, it is an independent software package. The authors are members of the GATE collaboration, but the GGEMS software is not part of the OpenGATE-supported software.

**Comment by Hoonly** [comment]
> > It said that 'GGEMS will be released in last trimester 2017' on the webpage, but until 2020, we can not find anything about it. Could you please give more information?
> 
> Hi @Hoonly , I wish I could. I recommend asking the authors, there are two contact email addresses on the GGEMS web page. Note that GGEMS is not part of GATE, it is an independent software package. The authors are members of the GATE collaboration, but the GGEMS software is not part of the OpenGATE-supported software.

Thanks, I will try to contact the authors directly.
