### ISSUE TITLE
Strings Broken in Binary Format

### ISSUE THREAD

**Issue by dfreese** [OpenGATE/Gate#141]
In the binary implementation of the output in [GateToBinary.cc](https://github.com/OpenGATE/Gate/blob/89a3b77f801b2c98cf24609306639b0d9fde07d7/source/digits_hits/src/GateToBinary.cc#L265-L270) (the hits output listed at that link) improperly writes out the G4String structure, rather than the contents of the string.  Below is the code used for Singles output on Line 825.

    m_outputFile.write( reinterpret_cast< char* >( &compVolName ), sizeof( G4String ) );

Using vGate, which I think used GCC (<v5.0) to compile on a 64bit system, the value written out 8 bytes of garbage.  [G4String](https://github.com/Geant4/geant4/blob/1a1316fea4d33260fe6fba9e5ece5149b9c877d0/source/global/management/include/G4String.hh#L59) in Geant (improperly) derives from std::string.  The implementation of std::string is compiler std library dependent, which means the sizeof(G4String) will differ between 32bit and 64bit platforms and different compliers.  The value, though, is wrong on every platform.

The proper format would be to chose a fixed number of characters to print so that each hit or single event is the same size in bytes, or to write out the string value like something this:

    m_outputFile.write(compVolName.c_str(), compVolName.length() + 1);

This is using the std::string interface, not the G4String interface.

I would prefer the fixed size that truncated after a point.  Currently the only way to not break the binary output for GATE compiled with GCC <v5.0 on 64 bit systems would be to truncate to 7 characters or fewer to have a null terminated string, or 8 if you would want to ignore that.  Anything else will break the current binary format.

Any preferences on how to fix this?

**Comment by dfreese** [comment]
(Asking because I'd be happy to write a fix if I knew what should be targeted)

**Comment by dsarrut** [comment]
Hello, 
could you check gcc version at compile time ? If it is below 5.0, restrict to 7 digits, if not use a user defined value ? What about clang compilator ? 

If in previous Gate version 7 digits were sufficient, maybe stay with 7 ? 

(I dont use GateToBinary so I cannot really help).

**Comment by dfreese** [comment]
My explanation may have added more confusion than necessary, sorry.

The current output contains invalid data, rather than the content of the strings.  The documentation on the wiki lists it as:

> Column N+17 : Name of the process which has generated the hit (8-bytes, G4string)
> Column N+18 : Name of the last volume where a Compton effect occured (8-bytes, G4string)
> Column N+19 : Name of the last volume where a Rayleigh effect occured (8-bytes, G4string)

I think the best way forward would be to put a c-style string in those 8 bytes (7 characters + '\0').  If the string is longer than 7 characters, we just truncate it, and note this as a bug in the documentation.  This way we do not break any scripts for anyone who uses the documentation. 

Perhaps the full string, or a wider c-style string could be adopted for GATE 9 (or earlier if appropriate), when the user might expect the output to change.

If that sounds okay, I will put together a patch?

**Comment by dsarrut** [comment]
ah, ok, sorry for my misunderstanding ! I fully agree with the c-style proposal (documentation may be changed in the wiki). Just ask if you need help for the PR

**Comment by dsarrut** [comment]
(PR PullRequest)

**Comment by dfreese** [comment]
My proposed fixed is now up.  Let me know if you have any comments.  Thanks!

**Comment by dsarrut** [comment]
Thanks perfect, thanks !
