### ISSUE TITLE
GateMiscFunctions.cc (l.88): Error while opening 

### ISSUE THREAD

**Issue by Ivan21Lopez** [OpenGATE/Gate#156]
I have a problem while I am triying o run one of the benchmarks in Gate, I am getting this:

eader read from       '/home/ivan/GATE/gate_v8.0/benchmarks/benchVoxelRegular25x25x25/maps/corps_cubique.h33'
 Data file name         '.. /maps/corps_cubique.i33'
 Nb of planes:           25
 Nb of pixels per plane: 25 25
 Pixel size:             1.200e+01 1.200e+01
 Slice thickness:        2.800e+01
 Matrix size:            3.000e+02 3.000e+02
 Data type:              UNSIGNED INTEGER
 Bytes per pixel:        2
 Data byte order:        LITTLEENDIAN
 Machine byte order:     LITTLEENDIAN

GateMiscFunctions.cc (l.88): Error while opening .. /maps/corps_cubique.i33 for reading.

**Comment by Supernabla** [comment]
First of all: I encourage you to use the [mailing list](http://www.opengatecollaboration.org/mailinglist) in doubt.

Concerning your problem: Did you build Gate with the option `GATE_DOWNLOAD_BENCHMARKS_DATA=ON`? I.e. does the binary `/home/ivan/GATE/gate_v8.0/benchmarks/benchVoxelRegular25x25x25/maps/corps_cubique.i33` exist? This would be a link to a file in the build directory of Gate.

**Comment by Ivan21Lopez** [comment]
Hello Simon

Thank you for answering, The benchmark folder  is inside  /gate_v8.0 directory and the bin file exists there,  I do not remember if I put ON during the install, benchmark folder should be in the build directory? Because it is not 

Do you want me to post this issue in the mailing list?

Regards
Iván 
 

Enviado desde mi iPhone

**Comment by Supernabla** [comment]
> Do you want me to post this issue in the mailing list?

Yes, I propose, that you write a mail to the mailing list, describing your problem in more details.

**Comment by dsarrut** [comment]
(not an issue, probably linked to the GATE_DOWNLOAD_BENCHMARKS_DATA option in the cmake)
