### ISSUE TITLE
License file ambiguous for most files

### ISSUE THREAD

**Issue by dfreese** [OpenGATE/Gate#159]
From the original [GATE reference](http://opengatecollaboration.org/sites/default/files/Jan2004.pdf), I understand that GATE should be licensed under the LGPL. 
 However the [license file](https://github.com/OpenGATE/Gate/blob/38cc0972e0478fc8a004a6f948dfd7adf1a26998/license/LICENSE.txt#L11) only references the include and source directories, which leaves the main repository as well as the benchmarks, cluster_tools, and cmake-modules directories ambiguous.  From the license file, it appears some things may be under the GPL, but it is unclear what those would be.

Can this be corrected to clarify the status of the rest of these files?

Thanks!

**Comment by dsarrut** [comment]
Done f057de5390db52818f1eaea516165e183a410f96 (LGPL is mostly for library but also apply to executable ; maybe a MIT licence should be more appropriated. To be discussed)

**Comment by dfreese** [comment]
Thank you @dsarrut for the detailed change!  I hope that didn't cause too much of a headache.

**Comment by dsarrut** [comment]
no problem: it was discussed during Steering Committee during the last OpenGate meeting last week to acknowledge the licence. Then, emacs did the job ;)
