### ISSUE TITLE
DoseActor bug

### ISSUE THREAD

**Issue by Eslam-Taha** [OpenGATE/Gate#163]
Greetings..
I was trying to use the command "setOverWriteFilesFlag" with the dose actor to have separate output file per run. The command works fine with dose and Edep output but not with number of hits as I get a single output

**Comment by djboersma** [comment]
link to gate-users discussion with example macro:
http://lists.opengatecollaboration.org/pipermail/gate-users/2017-December/010051.html

**Comment by dsarrut** [comment]
I will look at that early next year ...

**Comment by dsarrut** [comment]
Should be ok now with commit 460566db0711bf34bf25c6d3ac0a20554db49a03
