### ISSUE TITLE
the efficiency of tracking algorithm ?

### ISSUE THREAD

**Issue by Aziz2203** [OpenGATE/Gate#167]
Hello
what is the meaning of :
''the efficiency of tracking algorithm  (computation of the distance to the next boundary, 
search for the neighbouring voxels)''

**Comment by dsarrut** [comment]
where did you find that text ?

**Comment by Aziz2203** [comment]
in GATE users guide V8.0 
www.opengatecollaboration.org/sites/default/files/GATE-UsersGuideV8.0.pdf

**Comment by dsarrut** [comment]
Indeed it is really not clear ;) I don't understand neither ... Doc should be modified

**Comment by dsarrut** [comment]
I change a bit the text ... See here: http://wiki.opengatecollaboration.org/index.php/Users_Guide:Voxelized_Source_and_Phantom#Description_of_voxelized_geometry

**Comment by Aziz2203** [comment]
thank you very much David for the answer :)

2018-03-06 18:10 GMT+00:00 David Sarrut <notifications@github.com>:

**Comment by Aziz2203** [comment]
when I try the command:    ''source
/PATH_TO/geant4.10.03-install/bin/geant4.sh'' , i get this error :
"aucun fichier ou dossier de ce type'"


2018-03-24 16:03 GMT+00:00 oust aziz <aziz.oustous@gmail.com>:

**Comment by dsarrut** [comment]
Please use the mailing list for this type of questions, thanks
