### ISSUE TITLE
define a sensitive detector 

### ISSUE THREAD

**Issue by Aziz2203** [OpenGATE/Gate#171]
hello 
i want to know the meaning of  "vglue 1cm" in the following command : 

![28870512_1563006797152227_796049622555426816_o](https://user-images.githubusercontent.com/36993423/37221551-559184a6-23c2-11e8-8251-190acfba3d8b.png)

thank you in advance :)

**Comment by ustcfdm** [comment]
I have the same question. I checked the email archive. It seems to be a typo, and there should be no "vglue 1cm". Check the following link:
http://lists.opengatecollaboration.org/pipermail/gate-users/2012-July/005835.html

**Comment by dsarrut** [comment]
done #da524be744a9897a3a874686d1675913fa0b748f
