### ISSUE TITLE
GPU code needs work by experts

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#177]
When I tried to compile Gate with `GATE_USE_GPU=ON`, just to make sure that the upcoming release will actually compile with this option, I found out that it didn't, the compiler crashed with a segfault, and google tells me that this is due to an internal compiler bug which can be avoided with a very ugly workaround (add a -G flag). This is with the current release of CUDA, version 9.1. It's possible that `nvcc` in other CUDA versions does not have this bug; I don't have time to check all CUDA versions, I am not the GPU expert.

In #118 it was already reported that the list of compute capabilities is out of date. Actually, I wonder why this list is hard-coded, because I'd think that it should depend on which CUDA release you are using and on the actually available hardware (maybe the user should provide the list of relevant compute capabilities). If the maintainers do not have the time to check all (or at least several) CUDA versions and compute capabilities, then we should put some simple restrictions in the `CMakeLists.txt` file to allow a build only with the versions/capabilities that we can support, and document those restrictions in the wiki & release notes.

A more drastic solution is to disable the GPU code completely, if it turns out that we do not have the manpower to maintain it. That would be sad.

**Comment by dsarrut** [comment]
no more GPU code in the current version.
