### ISSUE TITLE
One error about Installing  GATE V8 

### ISSUE THREAD

**Issue by Aziz2203** [OpenGATE/Gate#179]
when I try the command:    ''source /PATH_TO/geant4.10.03-install/bin/geant4.sh'' , i get this error :        "aucun fichier ou dossier de ce type'"
![error1](https://user-images.githubusercontent.com/36993423/37866162-a9c97f2a-2f7e-11e8-89f7-8006d73f066c.png)

**Comment by dsarrut** [comment]
Hello, 

probably due to the space in the folder name ("Gate V8").
