### ISSUE TITLE
minimum CMake version

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#186]
For geant4, the minimum CMake version is 3.3, according to our own install wiki. Shouldn't we then also require that minimum version (or greater) in our own toplevel `CMakeLists.txt` file?

**Comment by bersbersbers** [comment]
Why? What about people who might use Geant4 precompiled binaries and don't compile Geant4 at all? Shouldn't they be able to use as old a Cmake version as possible?

**Comment by djboersma** [comment]
When running cmake for Gate, the G4_INSTALL_PATH/lib64/G4VERSION/*.cmake files need to be read. Those files are written in a build process that relies on a >3.3 cmake install. They do _not_ contain a "CMAKE_MINIMUM_REQUIRED" line, AFAICS in the install that I checked. So it's _conceivable_ that they can be read by older CMake versions. 

I think that the oldest CMake version that I still have on a system accessible by me is 2.8 (linux mint 17.3, based on ubuntu 14.04). I cannot check the build with the 2.4 version of CMake (unless I take the trouble of installing an ancient CMake version just for this purpose, which I am not quite willing to do, my time is limited....).

My worry about allowing older versions is that cmake has "policies" that define how the build is done, and these policies are version dependent. There is a mechanism to deal with that, but this is a lot of extra work. Newer CMake versions also introduce new commands, occasionally, we might want to use those if they are good for something and then it's a hassle to make a workaround for the older cmake versions. We lack manpower, so I'd prefer to limit the allowed cmake versions to a range that we can comfortably support.

**Comment by dsarrut** [comment]
See #337
