### ISSUE TITLE
error when instaling GATE 8.0

### ISSUE THREAD

**Issue by abdel510** [OpenGATE/Gate#187]
hello every one i am a student and i am new with using gate so i tried to install it i did instal geant4 10.3.3 and clhep then when i want to install gate i get this error 

[100%] Linking CXX executable Gate
/usr/bin/ld: _ZN5CLHEP12HepSymMatrix13adjustment6x6E: TLS definition in CMakeFiles/Gate.dir/source/externals/clhep/src/CLHEP/Matrix/SymMatrixInvert.cc.o section .tbss mismatches non-TLS definition in /home/abdel/Desktop/CLHEP/lib/libCLHEP.so section .bss
/home/abdel/Desktop/CLHEP/lib/libCLHEP.so: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/Gate.dir/build.make:17221: recipe for target 'Gate' failed
make[2]: *** [Gate] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/Gate.dir/all' failed
make[1]: *** [CMakeFiles/Gate.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

i tried with 8.1 and the same issue .
this is my gateconfiguration.h
/* GATE : configuration file */

#ifndef GATE_CONFIGURATION_H
#define GATE_CONFIGURATION_H
//This file is interpreted by cmake, to define macros based on the cmake configuration options
// Check : GATE_ANALYSIS_USE_FILE        = ON

#define GATE_USE_ROOT                 ON
/* #undef GATE_USE_OPTICAL */
#define GATE_ANALYSIS_USE_GENERAL     ON
#define GATE_ANALYSIS_USE_FILE        ON
/* #undef GATE_USE_LMF */
/* #undef GATE_USE_ECAT7 */
#define GATE_USE_GEANT4_UIVIS         ON
/* #undef GATE_USE_RTK */
/* #undef GATE_USE_ITK */
/* #undef GATE_USE_DAVIS */

#ifdef GATE_USE_ROOT
 #define G4ANALYSIS_USE_ROOT 1
#endif

#ifdef GATE_ANALYSIS_USE_GENERAL
 #define G4ANALYSIS_USE_GENERAL 1
#endif

#ifdef GATE_ANALYSIS_USE_FILE
 #define  G4ANALYSIS_USE_FILE 1
#endif

//#define G4VERSION                  10.3.3
#define G4VERSION_MAJOR              10
#define G4VERSION_MINOR              3
#define G4VERSION_PATCH              3
/* #undef GATE_USE_GPU */
/* #undef CUDA_FOUND */

#ifndef G4VERSION_MINOR
   #define G4VERSION_MINOR 0
#endif

#ifndef G4VERSION_PATCH
   #define G4VERSION_PATCH 0
#endif

// WARNING : Replace all G4VERSION_3 and other with a correct test
#if (G4VERSION_MAJOR > 9) || ((G4VERSION_MAJOR==9) && (G4VERSION_MINOR >=3))
   #define G4VERSION9_3 1
#endif

// WARNING : Replace all G4VERSION_3 and other with a correct test
#if (G4VERSION_MAJOR > 9) || ((G4VERSION_MAJOR==9) && (G4VERSION_MINOR >=6))
   #define Geant496_COMPATIBILITY 1
#endif

#define GATE_USE_OPENGL               TRUE

#endif // GATE_CONFIGURATION_H

thanks

**Comment by djboersma** [comment]
Hello Abdel,

Welcome to Gate!

First: what platform are you on (which linux distro, which release)? And do you know that we have a newer release, 8.1?

Second: This looks like there is a conflict between different CLHEP versions (locally installed and the CLHEP stuff shipped with Gate). Some questions:


1.       Which version is this CLHEP install that you have under /home/abdel/Desktop/CLHEP?

2.       What output do you get from the command: “printenv | grep CLHEP”, when you run this in the same shell as where you ran “make”?

3.       In cmake, did you set the GATE_USE_SYSTEM_CLHEP to ON or to OFF?

My suspicion is that you set that cmake variable to OFF but your LD_LIBRARY_PATH variable does contain /home/abdel/CLHEP/lib and somehow the build system gets confused by that. I must admit that I have never tested myself to build Gate with an external CLHEP library. Maybe we need to make the CLHEP part of our build system a bit more robust. Probably it has not been touched since very many years.

If my suspicion is correct, then there are two potential ways out: *either* you set the cmake flag to ON, *or* you remove /home/abdel/Desktop/CLHEP/lib from your LD_LIBRARY_PATH. In both cases you may need to run “make clean” before “make”, or start the build completely from scratch.

HTH,
David

**Comment by abdel510** [comment]
i have ubuntu 16.04 LTS. i know that there is gate 8.1 i tied it with geant4 10.4 and then with 10.3 than i thought that maybe i shoud install geant4 10.3 then i did uninstal the 10.4 then i tried again with gate 8.0 and 8.1 but i get the same error
1- my clhep is 2.3.4.3 by the way i tried the last version of it and i get the same error . now i am on 2.3.4.3 in /home/abdel/Desktop/CLHEP.
2- when i run  “printenv | grep CLHEP”  i get LD_LIBRARY_PATH=/home/abdel/Desktop/GEANT103/lib:/home/abdel/Desktop/ROOT/lib:/home/abdel/Desktop/CLHEP/lib
3 - GATE_USE_SYSTEM_CLHEP is set to OFF

**Comment by abdel510** [comment]
hello 
i instaled clhep for gate and geant4 only
now i tried A but i get the same error
but in B i did'nt add CLHEP in ld library or in bach file can you tell me how to remove it ? 
thanks

**Comment by djboersma** [comment]
`export LD_LIBRARY_PATH=/home/abdel/Desktop/GEANT103/lib:/home/abdel/Desktop/ROOT/lib`

**Comment by abdel510** [comment]
i tried B too with no luck i got the same error
[100%] Linking CXX executable Gate
/usr/bin/ld: _ZN5CLHEP12HepSymMatrix13adjustment6x6E: TLS definition in CMakeFiles/Gate.dir/source/externals/clhep/src/CLHEP/Matrix/SymMatrixInvert.cc.o section .tbss mismatches non-TLS definition in /home/abdel/Desktop/CLHEP/lib/libCLHEP.so section .bss
/home/abdel/Desktop/CLHEP/lib/libCLHEP.so: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/Gate.dir/build.make:17455: recipe for target 'Gate' failed
make[2]: *** [Gate] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/Gate.dir/all' failed
make[1]: *** [CMakeFiles/Gate.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by abdel510** [comment]
@djboersma can you tell me what to do ? thanks

**Comment by djboersma** [comment]
Did you start the build from scratch? The `CMakeCache.txt` file usually remembers your old settings, so if you only do that export command and then run make in the old build directory, then yes, I'd expect you to get the same error. The steps are:
1. make sure that `printenv | grep CLHEP` returns nothing, or at least nothing with paths.
2. create a new build directory
3. build (ccmake, make, make install)

**Comment by abdel510** [comment]
@djboersma yes i did that and the printenv didn't give any thing and i started the build from scratch in a new build directory but i get the same error.

can it be that i set ON in using clhep when installing geant4 ?

**Comment by djboersma** [comment]
ah, yes, if you set it to ON in geant4 then it should also be ON in Gate.
This would actually mean that it really should not be an option in Gate, it should just do the same thing as what geant4 is doing. But you already tried "A" and you wrote that it did not work. Did you start from scratch when you tried "A"?

**Comment by abdel510** [comment]
yes i did that i always start from scratch when it does not work

**Comment by abdel510** [comment]
@djboersma what should i do now ? i tried A and B from scratch

**Comment by djboersma** [comment]
You could try to rebuild geant4 with the system CLHEP option OFF and retry B.

**Comment by abdel510** [comment]
@djboersma i did install geant4 with OFF clhep and i installed gate with OFF too and it is working fine thanks for your help
