### ISSUE TITLE
GPU error: The volume 'no_attached_volume_given' cannot be found in the list of volumes. 

### ISSUE THREAD

**Issue by tfunck** [OpenGATE/Gate#188]
Hi,
I'm trying to run Gate on GPU using GPUEmisTomo. My .mac file works correctly when running on CPU, but I run into the following problem when trying to use GPU:

**GateObjectStore.cc (l.113): The volume 'no_attached_volume_given' cannot be found in the list of volumes. Abort.
Here is the list of available volumes : 
 LSO LYSO block crystal cylindricalPET endshielding head phantom_brain world**

Here "phantom_brain" refers to my voxelized brain phantom. If I change the "attachedVolumeName" defined on line 42 in physics/src/GateGPUEmisTomo.cc from "attachedVolumeName = "no_attached_volume_given";" to "attachedVolumeName = "phantom_brain";" and recompile, then I get the following error:

**2GateGPUEmisTomo.cc (l.361): phantom_brain is not a GateRegularParameterized.**

My voxelized phantom and source as follows : 

#################### VOXELIZED PHANTOM
/gate/world/daughters/name phantom_brain
/gate/world/daughters/insert ImageRegularParametrisedVolume
/gate/phantom_brain/geometry/setImage /home/users/tfunck/data/gm_L_2mm.txt
/gate/phantom_brain/geometry/setRangeToMaterialFile /data1/projects/info/range_atten_gm.dat

/gate/phantom_brain/placement/setTranslation  0. 0. 0. mm
/gate/phantom_brain/placement/setRotationAxis 1 0 0
/gate/phantom_brain/placement/setRotationAngle 0 deg
/gate/phantom_brain/attachPhantomSD

#################### VOXELIZED SOURCE
/gate/source/addSource voxel_brain GPUEmisTomo
/gate/source/voxel_brain/setGPUBufferSize  1000000
/gate/source/voxel_brain/setGPUDeviceID 1

/gate/source/voxel_brain/reader/insert image
/gate/source/voxel_brain/imageReader/translator/insert range
/gate/source/voxel_brain/imageReader/rangeTranslator/readTable /data1/projects/info/activity_range_gm.dat
/gate/source/voxel_brain/imageReader/rangeTranslator/describe 1
/gate/source/voxel_brain/imageReader/readFile /home/users/tfunck/projects/data/gm_L_2mm.txt

Is this a bug or have I made a mistake in defining my voxelized phantom/source? 

Thanks,

Thomas

**Comment by liaozhaishusheng** [comment]
I have same problem, and I try to modified the GateGPUEmisTomo.cc, want to see more information. However, I don't find something usefully.

**Comment by Lemechs** [comment]
Got the same problem as well on GATE/8.2. 
Any news/solutions on the matter?

**Comment by dsarrut** [comment]
Hello, sorry the GPU part is no more maintained ...
