### ISSUE TITLE
Incorrect wiki link to physics list builder mechanism

### ISSUE THREAD

**Issue by bersbersbers** [OpenGATE/Gate#189]
I get this warning:

> [Physic-0] WARNING: manual physic lists are being deprecated.
> Please, use physic list builder mechanism instead. Related documentation can be found at:
> http://wiki.opengatecollaboration.org/index.php/Users_Guide_V7.0:Setting_up_the_physics

However, "Users Guide V7.0:Setting up the physics" says "There is currently no text in this page."

**Comment by djboersma** [comment]
Hi! We removed old versions, we only provide the wiki that pertains to the latest release. Though much of the information should still be valid for old releases (and to be brutally honest: in some topics we are a bit slow in updating, so maybe some topics are more correctly explained for 7.0 than for 8.1).

So look here:
http://wiki.opengatecollaboration.org/index.php/Users_Guide:Setting_up_the_physics

Or here:
http://www.opengatecollaboration.org/sites/default/files/GATE-UsersGuideV7.0.pdf
Page 61.

**Comment by djboersma** [comment]
Ah yes, sorry! I blindly assumed that you were using version 7.0 and I am usually a bit impatient when we get questions about old releases. But this wrong link was still advertised in the develop version, you are totally right. So I think I fixed this now in the code, commit 991c42148439bba1e922848e910cd89bb0ef0aca. Thanks for keeping me alert!
