### ISSUE TITLE
'std:: bad_alloc' problem in Gate v8.1

### ISSUE THREAD

**Issue by bicerbaro** [OpenGATE/Gate#191]
Hello! I have just installed Ubuntu 18, Root 6.14.00, Geant 4.10.04.p02, RTK-1.4.0, ITK 4.13.0 and Gate v8.1.p01.

When I run a simulation in Gate, however, I get this message:

[Core-0] Initialization of physics
[Core-0] Initialization of actors
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

It looks like memory problem. However, my computer is only dedicated to Gate simulations (not tested with previous versions). I have an 128GB SSD HD  and DDR3 8GB Ram-Memory. 

Can anybody help me with this issue?

Thanks!

**Comment by bicerbaro** [comment]
My issue was solved. I had a 3D dose actor with a voxel size of 0.25 cm in every direction, attached to a box of 40 x 40 x 40 cm.  I believe this requires a lot of memory, so my hardware was not able to produce it.
I changed the box to 10x10x10cm and it worked fine...

**Comment by dsarrut** [comment]
Does it means 160x160x160 ? It is not a lot of memory, it should work. Are you sure it is not something else ? Or 0.25mm instead of cm ?

**Comment by djboersma** [comment]
Closing the issue, because apparently the user is happy.
