### ISSUE TITLE
Error when executing a visu.mac before intialization

### ISSUE THREAD

**Issue by MCvin** [OpenGATE/Gate#203]
I don't know if this is new but when the /control/execute visu.mac is done early in the main.mac this error occur:
[Core-0] Initialization of physics
[Core-0] Initialization of actors
GateImageT.icc (l.75): Unknown image file extension. Supported extensions are : 
.vox, .hdr, .img, .mhd, .mha, .h33, .i33, .dcm

This happens even when there is no image used in the macro so the error message is unlikely correct.

If the visu.mac is executed at the end, just before the application start. everything runs fine.

The problem seems to appear for any application with GATE 8.1.p01

**Comment by acuihua** [comment]
can i have a look at your files? and may find the error

**Comment by MCvin** [comment]
For example the error occur with this GateContrib example:
https://github.com/OpenGATE/GateContrib/blob/master/dosimetry/Radiotherapy/example2/
when running the macro file main-NPV1.mac with the visu (line 16 un-commented):
https://github.com/OpenGATE/GateContrib/blob/b7e3d0be41d0a2db5a94204899e65cb634d4d9b2/dosimetry/Radiotherapy/example2/mac/main-NPV1.mac#L16

The error has some randomness that I cannot explain. Sometimes it executes, sometimes it fails with the aforementioned error.

**Comment by dsarrut** [comment]
See #222
