### ISSUE TITLE
Store user guide source in git

### ISSUE THREAD

**Issue by EJEP** [OpenGATE/Gate#216]
Storing the user guide source code in the git repository would allow contributors to apply minor changes via pull requests. This would also have the advantage of distributing a versioned copy of the user guide 
with the source code.

Going forward, using a framework like that used by [ReadTheDocs](https://readthedocs.org/) would allow multiple versions of the user guide to be hosted as web pages rather than as pdfs. Something like this could be included on the [new website](https://github.com/OpenGATE/Gate/wiki/towards-new-website) or via a service like [ReadTheDocs](https://readthedocs.org/).

**Comment by EJEP** [comment]
I am happy to put the initial work in to convert the user guide source into a different format. I would suggest [ReStructured Text](http://docutils.sourceforge.net/rst.html) rather than markdown as it is a bit more powerful for writing technical documentation but maintains readability

**Comment by dsarrut** [comment]
Interesting ! However, is ReadTheDocs allow online text editor to allow users to do quick&easy web only pull request ?

**Comment by EJEP** [comment]
ReadTheDocs does not. However, it can hook into the GitHub so that when a commit is made to the source code, the web page is rebuilt. Links can be provided on each page to the source file on GitHub. The GitHub editor can then be used.

**Comment by mojca** [comment]
If you are thinking about porting the documentation, my super strong vote goes to **AsiiDoc**.

Don't use MarkDown unless you have very very very basic requirements, as almost anything beyond basic paragraphs, titles, images and just the most basic tables requires one kind of extension or another, usually simply hardcoding raw html, which is a difficult one to get rid of. AsciiDoc is really nicely structured and asciidoctor creates really nice html documents out of the box.

And yes, if you put the docs on GitHub, users can simply press the "Edit" button and automatically make a pull request (they need to have an account on GitHub, but they don't need to know any git whatsoever).

**Comment by EJEP** [comment]
I would rather use ReStructured Text as it is directly supported with readthedocs and looks a little more readable in the source compared to AsciiDoc while remaining similar enough in syntax to AsciiDoc to be understandable. I used http://hyperpolyglot.org/lightweight-markup for a comparison as I have no experience with AsciiDoc. Please tell me if this is not a fair comparison.

That said, I very much want to avoid a situation where there is a barrier to entry to maintaining and contributing to the user guide.

**Comment by EJEP** [comment]
Sure. Could you send me / give me access to the documentation source, so I can avoid doing too much typing? This isn't essential to get a first attempt going. I will need to check if I can import the repository to ReadTheDocs without being a member of the GitHub 'organization'

**Comment by dsarrut** [comment]
thanks a lot ! The doc source is the wiki (not git): http://wiki.opengatecollaboration.org/index.php/Users_Guide
For deploying the readthedocs site on the readthedocs server, you may try with your own GitHub account by cloning the gate repo, no ?

**Comment by EJEP** [comment]
Oh, yes, of course!

**Comment by EJEP** [comment]
An example site is available at https://gate-demo.readthedocs.io/en/readthedocs/index.html.

The pull request is #218

**Comment by dsarrut** [comment]
Very interesting thanks a lot ! Some comments: 
- there are some ads on the readthedocs site
- online edition seems feasible via the bottom right small menu. I tried the 'edit' link. It redirect nicely to the git page of the rst file. I tried to propose a change via a PR, but fail with 404 ...
- the search bar is useful (select page + highlight searched terms)

We will discuss with people in the collaboration about this idea and let you know. 

thanks again, 
David

**Comment by EJEP** [comment]
Regarding ads, it is possible to opt out of displaying them - see [here](https://docs.readthedocs.io/en/latest/advertising/ethical-advertising.html).

On the pull request issue, there was a box ticked in the settings restricting editing to collaborators. That may be the problem.

**Comment by mojca** [comment]
I'm not too familiar with readthedocs in particular, but I would like to point out that there are two independent questions / issues. The first and the most important one that's probably being suggested here is having documentation in a markup language that's easy to render for either web or PDF, next to the sources. (In my opinion there are only two really suitable formats which offer sufficient flexibility and complexity when needed: restructured text and asciidoc. I'm a fan of the second, but rst is also ok.)

The second part of the question is where to host the documentation once it's in a suitable format. I would probably use readthedocs as a secondary / backup location and host the primary pages on github or wherever your main site will be. So personally I would not worry about ads too much, but of course you can select the support the project, ending in win-win situation for both if you like the service.

@dsarrut: do you get the same kind of error if you try to edit one of the pages from, say, https://mesonbuild.com/ (the first one that came to my mind)?

**Comment by EJEP** [comment]
Was a decision ever made about this?

**Comment by dsarrut** [comment]
yes: we are switching to readthedocs (it was decided at the beginning of the summer). It is still work in progress, but it should soon replace the wiki. Hope within next weeks ...

**Comment by djboersma** [comment]
When i googled for "readthedocs opengate" I landed on this page:
https://readthedocs.org/projects/opengate/

When I click on "latest" then I land on our docs. But there is also a "stable" link, which leads to a useless page that might be discouraging for any interested new user. We either need a single link (to what is now called "latest") or make sure that "stable" points to something useful.

**Comment by tbaudier** [comment]
Hi @djboersma 

According to the doc, the stable link exists because the project contains tags and it point to the latest tag (but the doc does not exists at this moment):
https://docs.readthedocs.io/en/stable/versions.html

I deactivated the stable version for the moment in the parameters and I will reactivate it when the next version will be ok.

**Comment by tbaudier** [comment]
If you want access to the readthedocs parameters, send me an email with you readthedocs account name

**Comment by dsarrut** [comment]
done ! Thanks to everyone
