### ISSUE TITLE
genericRepeater

### ISSUE THREAD

**Issue by acuihua** [OpenGATE/Gate#237]
Hai, I had a problem when I use the genericRepeater. In the User Guide, it has an example:
#===========================
Rotation deg
Translation mm
0       0 1 0      0 0 10
10     0 1 0      0 0 10
15     0 1 0      0 0 20
#===========================
but when i use the command, it said  I should start with "Time", so I add "Time  s"  before "Rotation", but how many parameters for the commad? 
Thanks for your help!
Have a good day!

**Comment by djboersma** [comment]
Hi and welcome to GATE! The purpose of the GitHub issues is to report bugs, development comments/ideas and feature requests. For user support we have a dedicated "gate-users" mailing list. Could you please sign up to that list and ask your question there?

http://lists.opengatecollaboration.org/mailman/listinfo/gate-users
