### ISSUE TITLE
libImt.so: undefined reference

### ISSUE THREAD

**Issue by Milan991** [OpenGATE/Gate#254]
Hi,

I'm having following issue with compiling GATE V8.0.

```
user@user:~/Gate/gate_v8.0-build$ sudo make -j4
/home/user/root_v6.xx/lib/libImt.so: undefined reference to `tbb::interface7::internal::isolate_within_arena(tbb::interface7::internal::delegate_base&, long)'
collect2: error: ld returned 1 exit status
CMakeFiles/Gate.dir/build.make:17372: recipe for target 'Gate' failed
make[2]: *** [Gate] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Gate.dir/all' failed
make[1]: *** [CMakeFiles/Gate.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

Sistem configuration:
Ubuntu 18.04
gcc 7.4
root version 6.08 (also tried with 6.16 and 6.18)
Geant 4.10.03

Can someone tell me what can be the reason of this issue. I got stuck with this problem for months.
Thank you.
Regards,
Milan.

**Comment by Milan991** [comment]
I've solved this issue by updating libtbb2 and libtbb-dev to newer version with apt-get.

**Comment by Aversonkirk** [comment]
hello,I had the same question,did you make again after updated libtbb2 and libtbb-dev?
