### ISSUE TITLE
GATE 8.2 INSTALLATION Error

### ISSUE THREAD

**Issue by avenger88** [OpenGATE/Gate#255]
Hi when Im trying install gate8.2 using command : ccmake ./.   and when I want to configure , I see this error : 

 CMake Error at CMakeLists.txt:50 (MESSAGE):
   GATE should be compiled with a non-multithreaded installation of Geant4

Can anyone help me

**Comment by tbaudier** [comment]
Hi avenger88,

For this kind of question, you can use the mailing list next time, you will have a quicker answer:
http://www.opengatecollaboration.org/mailinglist

By the way, when you compile Geant4, deactivate GEANT4_BUILD_MULTITHREADED with ccmake.
