### ISSUE TITLE
genericRepeater documentation issue

### ISSUE THREAD

**Issue by smngr** [OpenGATE/Gate#263]
I'm trying to use a genericRepeater as documented here:
https://opengate.readthedocs.io/en/latest/defining_a_geometry.html#generic-repeater

I encountered two problems. Firstly, Gate informed me that my first line had to begin with 'Time'. Secondly, the rotations didn't seem correct.

Investigating the issue, I noticed that in GateMiscFunctions.cc there is a function ReadTimePlacements that the genericRepeater uses, which requires a 'Time' column prior to the rotation and translation info.

**Comment by dsarrut** [comment]
Done by PR #264
