### ISSUE TITLE
Question about the ct.mac 

### ISSUE THREAD

**Issue by S2NN** [OpenGATE/Gate#265]
Dear Gate-developers,
    I want to ask a question. I recently read the **ct.mac** file. I didn't understand what this part represents and didn't find the relevant description in USERS-GUIDE:
        /gate/source/xraygun/gps/energytype Arb
        /gate/source/xraygun/gps/histname arb
        /gate/source/xraygun/gps/histpoint  0.0100  7
        ......
       /gate/source/xraygun/gps/histpoint  0.0400  0 
        /gate/source/xraygun/gps/arbint Lin
Thank you.

**Comment by dsarrut** [comment]
Hello, it is linked to the Geant4 GPS (Global Particle Source), see (for example): http://www.sixiangguo.net/code/geant4/AppDevelop/ch02s07.html

**Comment by S2NN** [comment]
> Hello, it is linked to the Geant4 GPS (Global Particle Source), see (for example): http://www.sixiangguo.net/code/geant4/AppDevelop/ch02s07.html

Thank you!

**Comment by S2NN** [comment]
@dsarrut 
Tnank you!
