### ISSUE TITLE
Give the user the chance to declare actor properties the way he wants

### ISSUE THREAD

**Issue by BishopWolf** [OpenGATE/Gate#27]
In the file GateVImageActor in the void GateVImageActor::Construct()
you expect for the user to declare the size of the output matrix
(let's call it S), and the the user has to choose between resolution
(R) OR voxelSize (VS), being S = R * VS. This is an annoying behavior
for the user because you may know VS and R, and then you must multiply
to put in the actor the Size. So why not using any possible
combination? Solution is easy to implement.

Details

void GateVImageActor::Construct()
...
if (!mHalfSizeIsSet){
    mHalfSize = ComputeBoundingBox(mVolume->GetLogicalVolume()->GetSolid());
  }
  if (mResolutionIsSet && mVoxelSizeIsSet) {
    GateError("GateVImageActor -- Construct: Please give the
resolution OR the voxelsize (not both) for the sensor");
  }
  if (!mResolutionIsSet && !mVoxelSizeIsSet) {
    mResolution = G4ThreeVector(1.0, 1.0, 1.0);
    mResolutionIsSet = true;
  }

Can be replaced by

 if (!mHalfSizeIsSet){ //the user doesn't specify the size
          if (mResolutionIsSet && mVoxelSizeIsSet){ //but specify resolution
and voxelsize
                  mHalfSize = KroneckerProduct(mResolution, mVoxelSize)/2; //compute
size as the dot product of resolution and voxelsize
          }
          else { // also it doesn't specify one of the resolution or
voxelsize variables
                  mHalfSize =
ComputeBoundingBox(mVolume->GetLogicalVolume()->GetSolid()); // so get
size from the volume the actor is attached to
          }
          mHalfSizeIsSet = true; // say that size is set
  }
  else { // the user specify the size
          if (mResolutionIsSet && mVoxelSizeIsSet) { //but also the
resolution and the voxelsize so show an error
                  GateError("GateVImageActor -- Construct: Please give a combination
of two between" <<
                                    " the size, the resolution and the voxelsize (not all) for the sensor");
          }
  }

  if (!mResolutionIsSet && !mVoxelSizeIsSet) { // the size is defined
but neither the resolution nor the voxelsize, so use a default value
    mResolution = G4ThreeVector(1.0, 1.0, 1.0);
    mResolutionIsSet = true;
  }

So now any combination of two of this variables lead to a valid Image Actor.

**Comment by dsarrut** [comment]
Closed in #29
