### ISSUE TITLE
default module/submodule ID from 0 to -1

### ISSUE THREAD

**Issue by MarieleStockhoff** [OpenGATE/Gate#276]
Hi Gate Developers!

In an optical system with a module and a submodule the IDs are identical in ASCII output in the following cases:
1. Event in module (outside submodule): moduleID:0 submoduleID:0 
2. Event in module inside submodule: moduleID:0 submoduleID:0 

The problem is that in the first case there should be no submoduleID at all but the default value is 0. A potential fix is setting the default values to -1. Does this problem occur in other cases as well? Should all default values be -1?

![modulesubmoduleID](https://user-images.githubusercontent.com/39615596/73435382-cb8dde00-4348-11ea-9660-41822b56859a.png)

Best wishes,
Jens and Mariele

Jens.Maebe@UGent.be
Mariele.Stockhoff@UGent.be

**Comment by dsarrut** [comment]
I would say that submoduleID=0 in the first case is clearly a bug. 

A solution could, indeed, be to set it to an "empty" value that cannot be another real ID, so -1 as "empty" value could fit. The caveat is that maybe some code may always consider that submoduleID exists (which is wrong). 

My advice would be to make the change and set it to -1, but I don't know if it can break things or not. Please provide a PR with this change, I will test it against the benchmarks.

@djboersma : what do you think ?

**Comment by dsarrut** [comment]
see #316
