### ISSUE TITLE
Question about Geant10.5 installation

### ISSUE THREAD

**Issue by Marta-Coelho-109** [OpenGATE/Gate#280]
Good evening,

We are university students from Portugal. We are trying to install the Geant4 10.5 for our investigation project and we need to know which data files are required, for specific, optional physics processes. Which of these are mandatory for SPECT simulation with GATE V8.2.?

G4NDL4.5, Neutron data files with thermal cross-sections - version 4.5
G4EMLOW7.7, data files for low energy electromagnetic processes - version 7.7
G4PhotonEvaporation5.3, data files for photon evaporation - version 5.3 
G4RadioactiveDecay5.3, data files for radioactive decay hadronic processes - version 5.3
G4SAIDDATA2.0, data files from evaluated cross-sections in SAID data-base - version 2.0
G4PARTICLEXS1.1, data files for evaluated particle cross-sections on natural composition of elements - version 1.1
G4ABLA3.1, data files for nuclear shell effects in INCL/ABLA hadronic mode - version 3.1
G4INCL1.0, data files for proton and neutron density profiles in INCL - version 1.0
G4PII1.3, data files for shell ionisation cross-sections - version 1.3
G4ENSDFSTATE2.2, data files for nuclides properties - version 2.2 
G4RealSurface2.1.1, Optional data files for measured optical surface reflectance - version 2.1.1 
G4TENDL1.3.2, Optional data files for incident particles - version 1.3.2 
Accessed on the site: https://geant4.web.cern.ch/node/1765

Thank you for your attention.

**Comment by dsarrut** [comment]
(all files are needed) 
Hello, please use the mailing list. The issues are for code issues. thanks !
David
