### ISSUE TITLE
Warnings during compilation

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/Gate#281]
Hi @etxebest ,

I saw warnings during compilation. Can you explain the following lines to debug the code:

## warning: logical not is only applied to the left hand side of comparison

You committed this line:

https://github.com/OpenGATE/Gate/blame/develop/source/digits_hits/src/GateClustering.cc#L159

I have warnings when I compiled because the expression is misleading. How could you interpret that:
```
  if ((! outputPulseList.size()) > 1)
```
or
```
  if (! (outputPulseList.size() > 1))
```

## warning: this ‘if’ clause does not guard

You committed this line:

https://github.com/OpenGATE/Gate/blame/develop/source/digits_hits/include/GateLocalMultipleRejection.hh#L44

The identation or the brackets are not correct, so how do we understand the lines:

```
            if (policy!="volumeName") {
                G4cout<<"WARNING : policy not recognized, using default : volumeName for multiple consideration \n";
           }
           m_table[name].multipleDef = kvolumeName;
```
or
```
            if (policy!="volumeName") {
                G4cout<<"WARNING : policy not recognized, using default : volumeName for multiple consideration \n";
                m_table[name].multipleDef = kvolumeName;
            }
```

## warning: unused parameter ‘indent’

You committed:
https://github.com/OpenGATE/Gate/blame/develop/source/digits_hits/src/GateDualLayerLaw.cc#L124
and
https://github.com/OpenGATE/Gate/blame/develop/source/digits_hits/src/GateDepositedEnergyLaw.cc#L19

the indent variable is not used in these functions. Is it correct?
If the indent variable is necessary, to avoid the warning, we can add:
```diff
void GateDepositedEnergyLaw::DescribeMyself (size_t indent) const {
+  (void)indent
    G4cout << "Deposited energy  law \n"<< Gateendl;
}

```

Thank you

**Comment by tbaudier** [comment]
On mac, I have the following warnings:

## warning: unused parameter ‘...’

In:
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateCoincidenceTreeReader.hh#L46
and:
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateSequenceCoincidenceTreeReader.hh#L48

parameters:
```
    int evtID, coinID;
    double t;
    float energy,posX,posY,posZ;
    char lyrName[50];
```
are not used.
Can we remove them?

## Spanish words:

In:
https://github.com/OpenGATE/Gate/blob/develop/source/bin/GateDigit_singles_sorter.cc , 
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateCoincidenceTreeReader.hh
and
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateSequenceCoincidenceTreeReader.hh#L48
Some comments are in Spanish, could you translate them please?

Thank you

**Comment by djboersma** [comment]
If we are going to insist on English everywhere, then we should also translate the various instances of French in the code? :)

**Comment by tbaudier** [comment]
I am agree with you. It is just in the same part of the code she committed. 
By the way, if you encounter French words in the code, do not hesitate to send me a message, I will translate

**Comment by djboersma** [comment]
Hi @tbaudier : one notorious case is https://github.com/OpenGATE/Gate/blob/develop/source/physics/src/GateSourceLinacBeam.cc#L64 and at several places further down in that file. Notorious because there it is not only in the comments, also in the names of things in the phase space input file.

**Comment by dsarrut** [comment]
thanks!
