### ISSUE TITLE
How to make output sensitivity for PET-Compton?

### ISSUE THREAD

**Issue by Niel-sw** [OpenGATE/Gate#284]
I am trying to make simulation of PET-Compton. And i want to make the sensitivity PET and sensitivity Compton as the output. With the x-axis is the thickness of detector Compton and y-axis is the sensitivity (%) for PET, Compton. How to make that output? and should I place detector compton and detector PET in one cylinder or separate them?

**Comment by dsarrut** [comment]
Hello, please use the mailing list. The issues are for code issues. thanks !
David
