### ISSUE TITLE
GateDICOMImage.cc

### ISSUE THREAD

**Issue by Engpharaon** [OpenGATE/Gate#285]
Hi
I am trying to execute the mac file of dicom  example come with vgate 8.2 I always receive error cannot read the file ......
![15814212922401139973022](https://user-images.githubusercontent.com/28573914/74233894-4a353480-4cd4-11ea-91ea-8198f9dca08a.jpg)
Any one can help?
Regards 
Eng.Pharaon

**Comment by dsarrut** [comment]
Hello, please use the mailing list. The issues are for code issues. thanks !
David
