### ISSUE TITLE
Attach system error

### ISSUE THREAD

**Issue by Niel-sw** [OpenGATE/Gate#286]
![Screenshot at 2020-02-12 04-15-46](https://user-images.githubusercontent.com/57242765/74300012-c5d3c780-4d4e-11ea-8c19-e8eb8eb4922e.png)
I change the usual "CylindricalPET" to "cPET" and somehow it's show error on attach section. Any tips to fix this? 
Note: I use "cPET" for PET detector and "cCompton" for Compton detector. I separate those 2 into 2 daughters.
![s](https://user-images.githubusercontent.com/57242765/74300076-f9165680-4d4e-11ea-9567-4f9687042ebb.png)

**Comment by dsarrut** [comment]
Hello, please use the mailing list. The issues are for code issues. thanks !
David
