### ISSUE TITLE
Actor type: ComptonCameraActor doesn't exist! 

### ISSUE THREAD

**Issue by Niel-sw** [OpenGATE/Gate#291]
I have the issue with actor ComptonCameraActor. 
I am using vGate v8.2. I compile one of the main mac in GateContrib/imaging/ComptonCamera/ and the result show me "Actor type: ComptonCameraActor doesn't exist! ". I have check the code in the GateContrib with the one in Gate navigation and it's shouldn't be the problem. 
I attach the link for Gate navigation (Compton Camera Imaging) and the result from one of the main mac in GateContrib/imaging/ComptonCamera/.

https://opengate.readthedocs.io/en/latest/compton_camera_imaging_simulations.html

https://user-images.githubusercontent.com/57242765/74587539-0b64ee80-4ff4-11ea-94b6-74d7195f74d0.png

**Comment by etxebest** [comment]
Dear Niel,
The Compton Camera actor is a new implemented actor that will be 
included in the next GATE release. It is not  part of the version 8.2.
You can find it in the develop branch if you want to  use it.
Regards,
Ane

**Comment by Niel-sw** [comment]
Hello, @etxebest 
Can you tell me more spesific about develop branch? I hope it will useable in virtual gate since I really don't understand about install, compile for normal gate.
Thank you for your reply,
Daniel

**Comment by dsarrut** [comment]
Hi, you need to clone and compile Gate from the source code. If you don't know about install/compile, please wait for the next release and the next virtual machine 
thanks, 
David
