### ISSUE TITLE
example_Radiotherapy #10 broken - missing image file

### ISSUE THREAD

**Issue by k-joshi** [OpenGATE/Gate#30]
When attempting to build Gate 7.1 with CMake variable GATE_DOWNLOAD_EXAMPLES_DATA = ON, I receive the following error:

![screen shot 2015-06-04 at 15 20 19](https://cloud.githubusercontent.com/assets/12748422/7986111/5afd9ff8-0acd-11e5-9e00-9a42aec1b58c.png)

The file provided in example_Radiotherapy/example10/data appears to be "resampledTHORAX.raw", not phantom.raw.

Would it be possible to update example10 with the correct image file?

Many thanks

**Comment by dsarrut** [comment]
Solve in cc172725ce257d04107656ff349043603efd6e10

**Comment by dsarrut** [comment]
thanks to report, that should be ok now

David

On Thu, Jun 4, 2015 at 4:27 PM, k-joshi <notifications@github.com> wrote:

> When attempting to build Gate 7.1 with CMake variable
> GATE_DOWNLOAD_EXAMPLES_DATA = ON, I receive the following error:
>
> [image: screen shot 2015-06-04 at 15 20 19]
> <https://cloud.githubusercontent.com/assets/12748422/7986111/5afd9ff8-0acd-11e5-9e00-9a42aec1b58c.png>
>
> The file provided in example_Radiotherapy/example10/data appears to be
> "resampledTHORAX.raw", not phantom.raw.
>
> Would it be possible to update example10 with the correct image file?
>
> Many thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGATE/Gate/issues/30>.
>



-- 
David Sarrut, Phd
Directeur de recherche CNRS
CREATIS, UMR CNRS 5220, Inserm U 1044
Centre de lutte contre le cancer Léon Bérard
28 rue Laënnec, 69373 Lyon cedex 08
Tel : 04 78 78 51 51 / 06 74 72 05 42
http://www.creatis.insa-lyon.fr/~dsarrut
_________________________________
 "2 + 2 = 5,  for extremely large values of 2"
_________________________________
