### ISSUE TITLE
64Cu positron spectra problem

### ISSUE THREAD

**Issue by Tien-Phong-PHAM** [OpenGATE/Gate#312]
Dear Gate-users,

I’m trying to simulate the energy spectrum of a Cu-64 source using the ion definition in GATE v8.2, but i have a problem with the positron emission spectra. In fact, the energy distribution with my ion source is very different with spectral definition in the low energy region. I mean the energy spectrum of positron is similar to the energy spectrum of electron.

In this case, i just used the « RadioactiveDecay » as physics list

I would like to ask if someone has experience with ion type source can help me. 

Many thanks for your help !

![Spectrum Cu64 ](https://user-images.githubusercontent.com/60745128/75625581-bdd5ad80-5bbf-11ea-9d7a-a3db2edfb561.png)

**Comment by BishopWolf** [comment]
I think you just used the «RadioactiveDecay» as physics list. You also need to consider daughter decay using also the «Decay»

just add 

```
                #=====================================================
                # Physic List Mechanism
                #=====================================================

                /gate/physics/addPhysicsList	emstandard_opt4
                /gate/physics/addProcess RadioactiveDecay
                /gate/physics/addProcess Decay
```

**Comment by dsarrut** [comment]
Hi, thanks Alex. Tien-Phong-PHAM: is it solved now ?

**Comment by Tien-Phong-PHAM** [comment]
Hi David,

It's not the question of the physics list but a bug on version 8.2 I think
because I don't see this problem with version 9.

Sincerely
Tien-Phong PHAM

Le jeu. 17 déc. 2020 à 08:11, David Sarrut <notifications@github.com> a
écrit :

**Comment by dsarrut** [comment]
Hi, sorry, I think the issue was not clear for me ... can you be a bit more specific, please? What did you obtain and what are you expecting? 
Also, is the problem solved with the current version?
thanks!
