### ISSUE TITLE
empty ascii (and tree) hits output when using PhaseSpaceActor

### ISSUE THREAD

**Issue by mcristof** [OpenGATE/Gate#335]
Hi all,

when I add a PhaseSpaceActor 

/gate/actor/addActor PhaseSpaceActor                PhaseSpace1
/gate/actor/PhaseSpace1/attachTo                    phantom
/gate/actor/PhaseSpace1/save                        output/phs.root

the output of
/gate/output/ascii/enable
/gate/output/ascii/setFileName   output/test
/gate/output/ascii/setOutFileHitsFlag   1

(and the same for /gate/output/tree/)
is an empty file

without that Actor everything is ok.

Here the full code:

#=====================================================
# GEOMETRY
#=====================================================
/gate/geometry/setMaterialDatabase data/GateMaterials.db
/gate/world/geometry/setXLength 1. m
/gate/world/geometry/setYLength 1. m
/gate/world/geometry/setZLength 1. m
/gate/world/setMaterial Air
/gate/world/daughters/name              scanner
/gate/world/daughters/insert            box
/gate/scanner/geometry/setXLength       1 m
/gate/scanner/geometry/setYLength       1 m
/gate/scanner/geometry/setZLength       1 m
/gate/scanner/placement/setTranslation  0.0 0.0 0.0 cm
/gate/scanner/setMaterial               Air
/gate/scanner/daughters/name            phantom
/gate/scanner/daughters/insert          box
/gate/phantom/geometry/setXLength       40 cm
/gate/phantom/geometry/setYLength       40 cm
/gate/phantom/geometry/setZLength       1 cm
/gate/phantom/placement/setTranslation  0.0 0.0 10.0 cm
/gate/phantom/setMaterial               Water
/gate/phantom/repeaters/insert          linear
/gate/phantom/linear/setRepeatNumber    20
/gate/phantom/linear/setRepeatVector    0. 0. 10. mm
/gate/systems/scanner/level1/attach     phantom
/gate/phantom/attachCrystalSD
/gate/physics/addPhysicsList emstandard
#=====================================================
# ACTORS
#=====================================================
/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat-proton.txt
/gate/actor/addActor PhaseSpaceActor                PhaseSpace1
/gate/actor/PhaseSpace1/attachTo                    phantom
/gate/actor/PhaseSpace1/save                        output/phs.root
/gate/actor/PhaseSpace1/enableProductionProcess     true
/gate/actor/PhaseSpace1/storeSecondaries            false
/gate/actor/PhaseSpace1/addFilter                   particleFilter
/gate/actor/PhaseSpace1/particleFilter/addParticle  proton
#=====================================================
# INIT
#=====================================================
/gate/run/initialize
#=====================================================
# SOURCE
#=====================================================
/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle proton
/gate/source/mybeam/gps/pos/type Beam
/gate/source/mybeam/gps/pos/shape Circle
/gate/source/mybeam/gps/pos/centre 0 0 -20 cm
/gate/source/mybeam/gps/pos/sigma_x 0 mm
/gate/source/mybeam/gps/pos/sigma_y 0 mm
/gate/source/mybeam/gps/ene/mono 250 MeV
/gate/source/mybeam/gps/ene/type Gauss
/gate/source/mybeam/gps/direction 0 0 1
#=====================================================
# OUTPUT
#=====================================================
/gate/output/tree/enable
/gate/output/tree/addFileName output/p.npy
/gate/output/tree/addFileName output/p.root
/gate/output/tree/hits/enable
/gate/output/ascii/enable
/gate/output/ascii/setFileName   output/test
/gate/output/ascii/setOutFileHitsFlag   1
#=====================================================
# START BEAMS
#=====================================================
/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456
/gate/application/setTotalNumberOfPrimaries 100
/gate/application/start

thank you

**Comment by jasqs** [comment]
Hi,

I have the same issue. I found that any actor (even the SimulationStatisticActor) attached the the region that the crystal is attached to (phantom in @mcristof case) causes that the tree with hits and other is empty. I have checker that it is the same, regardless of the output format ASCI, root or numpy.

Could anyone help? I need to have the hits and PhaseSpaceActor at the same time.

best

**Comment by cpommranz** [comment]
This is probably related to #350.

**Comment by dsarrut** [comment]
Merge #354. Please @mcristof and @jasqs, could you check it it works now with the new PR ?
