### ISSUE TITLE
Phase Space Actor with multiple time slices

### ISSUE THREAD

**Issue by fkhellaf** [OpenGATE/Gate#341]
Hi,

I encountered an issue using Gate v9.0. There is a crash when I use a Phase Space Actor and more than one time slice. The problem does not occur when there is only one time slice, or if I remove the actor and use several slices.
Here is a minimal example:

# Geometry
/gate/geometry/setMaterialDatabase  data/GateMaterials.db
/gate/world/setMaterial             Vacuum
/gate/world/geometry/setXLength     20 m
/gate/world/geometry/setYLength     20 m
/gate/world/geometry/setZLength     20 m

# Physics list
/gate/physics/addPhysicsList QGSP_BIC

# Phase spaces
/control/alias DetectorName PhaseSpaceIn

/gate/world/daughters/name                            Plane{DetectorName}
/gate/world/daughters/insert                          box
/gate/Plane{DetectorName}/geometry/setXLength         1 nm
/gate/Plane{DetectorName}/geometry/setYLength         1000 mm
/gate/Plane{DetectorName}/geometry/setZLength         1000 mm
/gate/Plane{DetectorName}/setMaterial                 Vacuum
/gate/Plane{DetectorName}/vis/setVisible              1
/gate/Plane{DetectorName}/vis/setColor                yellow

/gate/actor/addActor PhaseSpaceActor                  {DetectorName}
/gate/actor/{DetectorName}/save                       output/{DetectorName}.root
/gate/actor/{DetectorName}/attachTo                   Plane{DetectorName}
/gate/actor/{DetectorName}/enableEkine                true
/gate/actor/{DetectorName}/enableXPosition            false
/gate/actor/{DetectorName}/enableYPosition            true
/gate/actor/{DetectorName}/enableZPosition            true
/gate/actor/{DetectorName}/enableXDirection           true
/gate/actor/{DetectorName}/enableYDirection           true
/gate/actor/{DetectorName}/enableZDirection           true
/gate/actor/{DetectorName}/enableProductionVolume     false 
/gate/actor/{DetectorName}/enableProductionProcess    false
/gate/actor/{DetectorName}/enableParticleName         false
/gate/actor/{DetectorName}/enableWeight               false
/gate/actor/{DetectorName}/enableTime                 true
/gate/actor/{DetectorName}/storeSecondaries           true
/gate/actor/{DetectorName}/useVolumeFrame             false
/gate/actor/{DetectorName}/storeOutgoingParticles     false
/gate/actor/{DetectorName}/addFilter                  particleFilter
/gate/actor/{DetectorName}/particleFilter/addParticle proton

/gate/Plane{DetectorName}/placement/setTranslation 400 0 0 mm

# Main
/vis/disable
/gate/run/initialize

# Beam
/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle       proton
/gate/source/mybeam/gps/ene/mono       200 MeV
/gate/source/mybeam/gps/ene/type       Mono
/gate/source/mybeam/gps/pos/type       Plane
/gate/source/mybeam/gps/pos/shape      Rectangle
/gate/source/mybeam/gps/pos/halfx      8 mm
/gate/source/mybeam/gps/pos/halfy      0.2 mm
/gate/source/mybeam/gps/pos/centre     1060 0 0 mm
/gate/source/mybeam/gps/direction      -1 0 0
/gate/source/mybeam/gps/ang/type       focused
/gate/source/mybeam/gps/ang/focuspoint 1000 0 0 mm

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto

/gate/application/setTimeSlice              0.5 s
/gate/application/setTimeStart              0 s
/gate/application/setTimeStop               10 s

/gate/application/setTotalNumberOfPrimaries 10
/gate/application/start

Also, when I try to save the Phase Space as a numpy array or a txt file rather than a root file, there is no crash but only a single particle is written in the file.

Thank you

**Comment by tbaudier** [comment]
Hi,
With a git bisect, I found the blaming commit:
https://github.com/OpenGATE/Gate/commit/43cc7c7933ea915a348c3cef00727deaa28a84ed

**Comment by dsarrut** [comment]
See #342
