### ISSUE TITLE
Scintillation Process does NOT work in GATEv9.0

### ISSUE THREAD

**Issue by hangyookang** [OpenGATE/Gate#346]
Scintillation Process does NOT work in GATEv9.0

Recently, I installed GATEv9.0 on my Ubuntu Linux PC with Geant4 10.06.p02.
The "GATE_USE_OPTICAL" option was turned ON during the installation.

After GATE installation, I checked that everything works fine except the scintillation process.
The optical.mac in the benchImaging folder is working well as it uses "opticalphoton" as a source.
I checked that Cerenkov process is also working.
However, "Scintillation Process" is NOT working in GATEv9.0 optical simulation.

Is there any one who validated in "scintillation process" in GATEv9.0?

**Comment by wrzof** [comment]
Hi, 

For me either, the combination gatev9 + geant4 10.06 doesn't produce scintillation. I advice you to use geant4 10.05 for the moment. We will try to figure out what it is happening. 

In release note of geant4 10.06 (http://geant4-data.web.cern.ch/geant4-data/ReleaseNotes/ReleaseNotes4.10.6.html), I only found a mention to scintillation : 

> G4Cerenkov, G4Scintillation, G4SynchrotronRadiation, G4VTransitionRadiation: added registration/de-registration mechanism.

For now, I do not know if it is related to our problem.

**Comment by hangyookang** [comment]
Thanks for your advice on the scintillation process of GATEv9.0

I'll try to use the combination of GATEv9.0 and Geant4.10.05 for the scintillation process in GATE.

Hopefully, the scintillation process issue will be resolved in the next release of GATEv9.1.

Best regards,

Han Gyu

**Comment by wrzof** [comment]
@hangyookang  I proposed a fix in #368, can you test if it solves your problem ?

**Comment by hangyookang** [comment]
Fortunately, the scintillation process works well after recompile the GATEv9.0 with Genat4.9.05.p01 as attached PDF file.

In summary 
(Before)GATEv9.0 + Geant4.10.06.p02 -> Scintillation Process does NOT work.
(After)  GATEv9.0 + Geant4.9.05.p01 -> Scintillation Process does work.

Thank you for your good advice~!

Best regards,

Han Gyu Kang
[GATEv9p0 Scintillation Process Works with Geant4.9.05.p01(2020_10_21_KangHG_v0).pdf](https://github.com/OpenGATE/Gate/files/5416308/GATEv9p0.Scintillation.Process.Works.with.Geant4.9.05.p01.2020_10_21_KangHG_v0.pdf)

**Comment by dsarrut** [comment]
Please, can you test with GATEv9.0 + Geant4.10.06.p02 and the patch #368 ? 
thanks, 
David

**Comment by dsarrut** [comment]
fixed in #368, thanks !

**Comment by hangyookang** [comment]
Dear Mathieu, and David,

Today I checked the scintillation process works well with the combination of GATEv9.0 and Geant410.06.p02 thanks to the path #368.

Best regards,

Han Gyu Kang
