### ISSUE TITLE
RTK Error in SPECT_FFD Example

### ISSUE THREAD

**Issue by miriam-mc** [OpenGATE/Gate#351]
Hello,

I am having trouble running the SPECT_FFD example in GateContrib. When I run the example that is provided with vGate V9.0 without any modification, it gives the following error:
GateFixedForcedDetectionActor.cc (l.1575): RTK requires equal source-to-center and center-to-detector distances in parallel geometry

I have tried changing various translation and placement values but the error has not gone away and I am not familiar enough with RTK to know what else to try, especially as the error is present with the original example.

Cheers,
Miriam

**Comment by tbaudier** [comment]
Hi @miriam-mc,

I looked into your problem without solve it totally.
But, I have the same error than you; the error can be see here:
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/src/GateFixedForcedDetectionActor.cc#L1575

So to deal with this error I modify the line https://github.com/OpenGATE/GateContrib/blob/master/imaging/SPECT_FFD/mac/fixedForcedDetectionSPECT.mac#L59 to:
`/gate/source/gammaSource/gps/centre -60.7625 0. 0. cm`

Then I obtain the error https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/src/GateFixedForcedDetectionActor.cc#L1580.
To deal with it I modify the line:
https://github.com/OpenGATE/GateContrib/blob/master/imaging/SPECT_FFD/mac/fixedForcedDetectionSPECT.mac#L11
to
`/gate/crystalVolumeFFD/placement/setRotationAxis    0  0 1 `

But it fails latter.

@SimonRit @dsarrut does the orientation in Geant or RTK have changed and could explain the error?

Thomas

**Comment by SimonRit** [comment]
Hi Thomas,
Thanks for looking into it. There might have been some minor evolutions in RTK but the errors never reach RTK's code... The example had been designed to pass those checks and the example has not been modified so something in Gate is behaving differently (or the example never worked?).
Simon

**Comment by SimonRit** [comment]
Parallel geometry has been allowed in the FFD actor under specific circumstances and a check added when Fresnel phase contrast propagator had been implemented (in #170). This check is not valid for SPECT and has been disabled then by #538.
