### ISSUE TITLE
IonSource energy default is 1 MeV (not 0 MeV)

### ISSUE THREAD

**Issue by dsarrut** [OpenGATE/Gate#358]
When using an ion source with the GPS, if the energy is not explicitly set, it is 1 MeV. 

This is because the Gate class https://github.com/OpenGATE/Gate/blob/develop/source/physics/src/GateSPSEneDistribution.cc inherit from this G4 class: http://www.apc.univ-paris7.fr/~franco/g4doxy/html/classG4SPSEneDistribution.html that default energy to 1 MeV. 

Maybe we should change this default, or (better) require the user to explicitly set the energy?

**Comment by BishopWolf** [comment]
I think default shall be 0 MeV. Ion source is used a lot to provide radioactive decay where energy different from 0 makes no sense. For other applications you must set your energy.

**Comment by dsarrut** [comment]
done, see PR #366

**Comment by dsarrut** [comment]
TODO: force user to set an Energy, no default value
