### ISSUE TITLE
program exit without any output or warning or error

### ISSUE THREAD

**Issue by Hoonly** [OpenGATE/Gate#360]
I am learning CT simulation using Gate, when I simulated a whole 360degs projection, I found there are some problems like that:

the speed of my phantom was set to 1 deg/s
when the total number of  primaries were set to **1e9** and time slice was set to
_setTimeSlice  1 s
setTimeStart  270 s
setTimeStop  271 s_
after running serveral seconds, the program exit without any output file and any warning or error, just end of macro. From the info in the terminal, I think everthing were initialized successfully.

But when the total number of  primaries were reduced to **1e6** or **1e7**, everthing was ok, I got correct output.

Then I tried to get the 270th projection in another way:
At the beginning, rotate the phantom to 270 deg, the speed of  phantom was set to 1 deg/s, and time slice was set to
_setTimeSlice  1 s
setTimeStart  0 s
setTimeStop  1 s_
the total number of  primaries were set to **1e9**, then the program running correctly, and I got the 270th projection output.

And there is a third way which I got the 270th projection output correctly:
Just set the speed of  phantom to 270 deg/s, and time slice was set to
_setTimeSlice  1 s
setTimeStart  1 s
setTimeStop  2 s_
the total number of  primaries were set to **1e9**.

I think the first way should be used normally, but it can not running as expected, I wonder why this happened.

The installed Gate was 9.0, with Geant4 10.06p2 and ROOT6

**Comment by wrzof** [comment]
Hi, 

can you provide a minimal example ?

**Comment by Ynskbz** [comment]
Bonjour , 
j'ai le meme probleme des particules primaires des que je lance un nombre superieur à 1e9 le programme tourne rapidement sans aucune sortie ! 
application linac radiotherapy

**Comment by Ynskbz** [comment]
j'utilise la veriosn v8.2 de GATE
