### ISSUE TITLE
"Illegal Application State" error when running Gate Fluorescence example

### ISSUE THREAD

**Issue by Nazarimasoumeh** [OpenGATE/Gate#361]
It is interesting that running its own example of fluorescence encounters "Illegal Application State". Does anybody have an idea what is this error? It is when defining the source.
![photo_2020-10-02_02-12-22](https://user-images.githubusercontent.com/72247665/94897962-8d2f5c80-049d-11eb-9f94-db96011b25dd.jpg)

**Comment by SimonRit** [comment]
A macro file would help for identifying the problem. I'm guessing that you need to define your beam after the line
`/gate/run/initializePlease`
prefer the [mailing list](http://www.opengatecollaboration.org/mailinglist) for such questions, github issues are for identified bugs.

**Comment by SimonRit** [comment]
Sorry, I did not read your post carefully enough. you are actually referring to an example in GateContrib... I'm reopening the issue
