### ISSUE TITLE
G4RadioactiveDecay is being deprecated

### ISSUE THREAD

**Issue by BishopWolf** [OpenGATE/Gate#362]
[Radioactive Decay](https://github.com/OpenGATE/Gate/blob/f2d9a5e19d568c71fe11b64a05d4f6037a208841/source/physics/src/GateRadioactiveDecayPB.cc#L28) is being deprecated in Geant4 with the following warning

```
G4RadioactiveDecay is deprecated and will be removed in Geant4 version 11.
 Please replace it with G4RadioactiveDecayBase if you want the unbiased radioactive deacy process.
 If you want the general process, with optional biasing, use G4Radioactivation.
```
That line shall be changed to 

```
return new G4Radioactivation(GetG4ProcessName());
```
and test if everything still works

**Comment by BishopWolf** [comment]
Changes in [this PR](https://github.com/OpenGATE/Gate/pull/363) are the way to go. It still need testing but it works from my side in my macros.

**Comment by dsarrut** [comment]
close with #363
