### ISSUE TITLE
Docker Gate 9.0 QT mode doesn't work

### ISSUE THREAD

**Issue by David-Morales-Norato** [OpenGATE/Gate#364]
Hi all

Im just install Gate 9.0 using the docker container given by the oficial OpenGATE web. It seems that there isn't an error, how ever i can't use the QT mode

### This is how i launch GATE 

`$ docker run -it opengatecollaboration/gate:9.0`

root@8b48e0868106:/# `Gate --qt`

### This is the output:

[G4] 
[G4] **************************************************************
[G4]  Geant4 version Name: geant4-10-06-patch-01    (14-February-2020)
[G4]                        Copyright : Geant4 Collaboration
[G4]                       References : NIM A 506 (2003), 250-303
[G4]                                  : IEEE-TNS 53 (2006), 270-278
[G4]                                  : NIM A 835 (2016), 186-225
[G4]                              WWW : http://geant4.org/
[G4] **************************************************************
[G4] 
[Core-0] Initialization of geometry
[Core-0] Initialization of physics
[Core-0] Initialization of actors
[Core-0] 
[Core-0] *************************************************
[Core-0]  GATE version 9.0 (March 2020)
[Core-0]  Copyright : OpenGATE Collaboration
[Core-0]  Reference : Phys. Med. Biol. 49 (2004) 4543-4561
[Core-0]  Reference : Phys. Med. Biol. 56 (2011) 881-901
[Core-0]  Reference : Med. Phys. 41(6)    (2014)
[Core-0]  http://www.opengatecollaboration.org        
[Core-0] *************************************************
[Core-0] 
[Core-0] You are using Geant4 version 10.6.1
[G4] Graphics systems deleted.
[G4] Visualization Manager deleting...
root@8b48e0868106:/# 

As you can see GATE closes inmediatily.

My issue is that i need to see how is the setup of my simulation. 
**Do i have to configure something in docker or in GATE to be able of visualize my simulations?**

Thanks for your help. :D

**Comment by tbaudier** [comment]
Hi @David-Morales-Norato ,

I never tried the Gate docker but with what you described I can tell 2 things:
 - I'm not sure Geant4 (and Gate) was compiled with qt inside the docker. Maybe someone else can help.
 - I already used Docker and when I wanted to display something from the Docker I need to start the command line with ```docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix```. I'm not a specialist of Docker, maybe there is another way to have a visual feedback

I hope it can help you a bit

**Comment by BishopWolf** [comment]
Same here, qt is not working in docker image even with x11 forwarding

```
[alex@alex-b450aoruselite ~]$ docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix opengatecollaboration/gate:9.0
Unable to find image 'opengatecollaboration/gate:9.0' locally
9.0: Pulling from opengatecollaboration/gate
5bed26d33875: Pull complete 
f11b29a9c730: Pull complete 
930bda195c84: Pull complete 
78bf9a5ad49e: Pull complete 
372cc52d05a4: Pull complete 
a06ce2bc70b5: Pull complete 
44edc88c154c: Pull complete 
bf5b8f242b18: Pull complete 
5421be6a2d9a: Pull complete 
15e4d2f69673: Pull complete 
a888f41bd672: Pull complete 
Digest: sha256:83d629dd799107def330ad14ab2d5c94a2dedfdef8d7773236cd514be0b76223
Status: Downloaded newer image for opengatecollaboration/gate:9.0
root@504aa350d17e:/# Gate --qt
[G4] 
[G4] **************************************************************
[G4]  Geant4 version Name: geant4-10-06-patch-01    (14-February-2020)
[G4]                        Copyright : Geant4 Collaboration
[G4]                       References : NIM A 506 (2003), 250-303
[G4]                                  : IEEE-TNS 53 (2006), 270-278
[G4]                                  : NIM A 835 (2016), 186-225
[G4]                              WWW : http://geant4.org/
[G4] **************************************************************
[G4] 
[Core-0] Initialization of geometry
[Core-0] Initialization of physics
[Core-0] Initialization of actors
[Core-0] 
[Core-0] *************************************************
[Core-0]  GATE version 9.0 (March 2020)
[Core-0]  Copyright : OpenGATE Collaboration
[Core-0]  Reference : Phys. Med. Biol. 49 (2004) 4543-4561
[Core-0]  Reference : Phys. Med. Biol. 56 (2011) 881-901
[Core-0]  Reference : Med. Phys. 41(6)    (2014)
[Core-0]  http://www.opengatecollaboration.org        
[Core-0] *************************************************
[Core-0] 
[Core-0] You are using Geant4 version 10.6.1
[G4] Graphics systems deleted.
[G4] Visualization Manager deleting...
root@504aa350d17e:/#
```

**Comment by David-Morales-Norato** [comment]
@BishopWolf , i find the same, it seems the docker version doesn't have qt compiled, the solution that i think will work for me is use the GATE 8.2 VM to visualize the gemoetry and everithing, and then run the simulation in the 9.0v.
