### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by ustunkubra** [OpenGATE/Gate#377]
Hi, i have Geant4 10.6.2 on my computer and  GATE 9.0was compatible with Geant4 10.6; but when i try to install it i see the warning below:
![image](https://user-images.githubusercontent.com/44575534/99183245-3cfd1880-2732-11eb-9429-8b595c79b8d2.png)
Should i install another version of Geant4 or can i do something else?

**Comment by tbaudier** [comment]
Hi @ustunkubra ,

During the compilation of Geant4, the multithread build should be disable:

<img width="256" alt="Screenshot 2020-11-16 at 09 24 58" src="https://user-images.githubusercontent.com/15010467/99228917-9b3b0180-27ed-11eb-9ce2-924e4132f137.png">

You can found this option in the advanced mode in ccmake.
After that, recompile Geant4 and the you sould be able to compile Gate

**Comment by ustunkubra** [comment]
Thank you so much, i installed geant4 10.6.p03 and did that, but now am having trouble with root. I have python on my device but root can't see it and gives error mesages.

**Comment by tbaudier** [comment]
Hi @ustunkubra ,
To use root for Gate, you can deactivate python (and/or python3) options in ccmake. It's not necessary for Gate

**Comment by ustunkubra** [comment]
Hello again, sorry for being so unknowing about this, but right now i'm installing root again and i see this message after configuring normally: 
![image](https://user-images.githubusercontent.com/44575534/99386557-939d5a80-28ca-11eb-95c8-0e46535b9895.png)

and that message after deleting python directory usin advanced options:
![image](https://user-images.githubusercontent.com/44575534/99386630-afa0fc00-28ca-11eb-8818-d8faf663dad8.png)
how do i deactivate python?

**Comment by djboersma** [comment]
@ustunkubra : could you delete the `CMakeCache.txt` file (in the ROOT build directory) and try again?

**Comment by ustunkubra** [comment]
but i did that when build directory was empty using the command ccmake../root-source
while that screen was open i deleted it and added python_executable again , when i configured i saw that again:
![image](https://user-images.githubusercontent.com/44575534/99390898-4375c680-28d1-11eb-9ae5-e4450451370b.png)
