### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by uhqd** [OpenGATE/Gate#394]
Hi all

I cloned the current develop branch of GATE (last commit).

I use the vGate 9.0 on a virtual machine sucesfullyt but I need a more recent commit that fixed a bug (phsp error when multiclice is used) so I need to upgrade Gate

First my cmake was too old (3.10) so I upgraded cmake to 3.18...ok.

But when I try to compile I have the following error. 

Is is an issue with my ITK version ??? 

Thank you very much

This is my cmake command
sudo -E cmake \
>            -DGeant4_DIR=${Geant4_DIR} \
>            -DCMAKE_INSTALL_PREFIX=../Gate-install \
>            -DGATE_USE_ITK=ON \
>            -DITK_DIR=/home/gate/Softwares/ITK/build \
>            -DGATE_USE_RTK=ON \
>            -DGATE_USE_OPTICAL=OFF \
>            -DGATE_USE_TORCH=ON \
>            -DTORCH_DIR=/home/gate/Softwares/libtorch/share/cmake/Torch \
>            ../Gate;

This is my compilation error message. 

/usr/share/gate-dev/Gate/source/digits_hits/src/GateFixedForcedDetectionActor.cc: In member function ‘virtual void GateFixedForcedDetectionActor::SaveData(G4String)’:
/usr/share/gate-dev/Gate/source/digits_hits/src/GateFixedForcedDetectionActor.cc:1180:58: error: ‘itk::FFTFilterType<itk::Image<std::complex<float>, 3> >**::TransformDirectionEnum’ has not been declared**
     fftFilterImage->SetTransformDirection(FFTFilterType::TransformDirectionEnum::FORWARD);
                                                          ^~~~~~~~~~~~~~~~~~~~~~
/usr/share/gate-dev/Gate/source/digits_hits/src/GateFixedForcedDetectionActor.cc:1191:64: error: ‘itk::FFTFilterType<itk::Image<std::complex<float>, 3> >::TransformDirectionEnum’ has not been declared
     fftFilterOutputImage->SetTransformDirection(FFTFilterType::TransformDirectionEnum::INVERSE);

**Comment by SimonRit** [comment]
Yes, this is an ITK issue. The solution is to upgrade ITK to the latest
release. Or to disable RTK and ITK if you don't need them.

**Comment by uhqd** [comment]
Wow !!! 3 minutes and I have a good answer!! Thank you Simon... Well i successfully compiled without ITK/RTK... Too lazy to change my itk version... I Wait for Gate9.1 !! I do not want to ask too much but if you have a small script to upgrade itk, it would be very nice...
