### ISSUE TITLE
M_PI is no longer part of C99

### ISSUE THREAD

**Issue by mojca** [OpenGATE/Gate#4]
M_PI is no longer part of C99 and some compilers no longer support it. It should be defined if it doesn't exist yet.

At some places it is already defined as:

    source/digits_hits/src/GateToGPUImageSPECT.cc:
    #define PI ( 4 * ::atan( 1 ) )

See also:
- https://its.cern.ch/jira/si/jira.issueviews:issue-html/CLHEP-125/CLHEP-125.html

**Comment by BishopWolf** [comment]
I think this issue no longer stands, so I recommend to close it
