### ISSUE TITLE
LibTorch compilation problem

### ISSUE THREAD

**Issue by Hoco0807** [OpenGATE/Gate#401]
Hi everyone：

During Gate compilation, after I turned on GATE_USE_TORCH, I encountered ‘cmake error’ during compilation. The ccmake compilation interface is shown in the figure below.
The system parameters are: Ubuntu18.04.5 LTS, GATE V9.0, and CUDA 10.2
######################################################
The error message is as follows:
CMakeFiles/GateLib.dir/build.make:12614: recipe for target 'CMakeFiles/GateLib.dir/source/digits_hits/src/Gate_NN_ARF_Actor.cc.o' failed
make[2]: *** [CMakeFiles/GateLib.dir/source/digits_hits/src/Gate_NN_ARF_Actor.cc.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/GateLib.dir/all' failed
make[1]: *** [CMakeFiles/GateLib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by 2270284704** [comment]
Hi there, I just encountered this problem too, do you still remember how its been solved? thank you:)
