### ISSUE TITLE
Compiling Torch error

### ISSUE THREAD

**Issue by Hoco0807** [OpenGATE/Gate#404]
Hi all:
    I followed these instructions: https://opengate.readthedocs.io/en/latest/compilation_instructions.html#libtorch-optional, and I completed the compilation of Gate. There are a warning during compilation: "warning: ISO C++11 requires at least one argument for the "..." in a variadic macro". I ignored this warning and proceeded to the next installation. When i run the Gate program, a prompt appears: "Gate: error while loading shared libraries: libtorch.so: cannot open shared object file: No such file or directory
". 
I tried to use 'ldconfig' to link /libtorch/lib', but the same error was still reported. I don't know how to solve this error, I hope everyone can give me some suggestions.
The system i use is: ubuntu18.04.5 LTS, and install libtorch 1.4.0 into Gate9.0.
Best wish.

**Comment by dsarrut** [comment]
Hello, can you please indicate the values of the following cmake variables: Torch_DIR, TORCH_LIBRARY ? 
I suppose you use the source code from the 'develop' branch of the git ? 
David

**Comment by Hoco0807** [comment]
> Hello, can you please indicate the values of the following cmake variables: Torch_DIR, TORCH_LIBRARY ?
> I suppose you use the source code from the 'develop' branch of the git ?
> David

Hello David:
Thank you very much for your reply.
The configuration of the 'Torch_DIR' path is followed by referring to the Gate manual. And the path of 'TORCH_LIBRARY' is automatically generated. The Torch configuration path is:
Torch_DIR = /opt/libtorch/share/cmake/Torch
TORCH_LIBRARY = /opt/libtorch/lib/libtorch.so
For the source code, I downloaded it from the website below.
https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
Best wish, 
huangchuan

**Comment by dsarrut** [comment]
it seems that libtorch.so is not found at run time. Maybe try to look at the LD_LIBRARY_PATH env variable to check if the folder /opt/libtorch/lib/ is in ?
