### ISSUE TITLE
Gate's graphical interface does not work and a Benchmark Test error

### ISSUE THREAD

**Issue by haima991027** [OpenGATE/Gate#406]
**Dear all
I was having problems with the graphical interface when using Gate.
Because I'm newer of GATE, but I also Googled my question, and I'm sorry if my question was stupid.
After the GATE installation was complete, I ran a Benchmark Test and the result as follow:**

Test project /home/asus/zhm/gate/Gate-9.0/build
    Start 1: FIRST_EXECUTION_TEST
1/7 Test #1: FIRST_EXECUTION_TEST .............   Passed    4.82 sec
    Start 2: benchRT_gamma
2/7 Test #2: benchRT_gamma ....................***Failed   10.75 sec
    Start 3: benchRT_proton
3/7 Test #3: benchRT_proton ...................***Failed    1.30 sec
    Start 4: benchRT_carbon
4/7 Test #4: benchRT_carbon ...................***Failed    4.87 sec
    Start 5: benchImaging_ct
5/7 Test #5: benchImaging_ct ..................***Failed   10.33 sec
    Start 6: benchImaging_optical
6/7 Test #6: benchImaging_optical .............   Passed    0.95 sec
    Start 7: benchImaging_spect
7/7 Test #7: benchImaging_spect ...............***Failed   17.24 sec

29% tests passed, 5 tests failed out of 7

Total Test time (real) =  50.27 sec

The following tests FAILED:
          2 - benchRT_gamma (Failed)
          3 - benchRT_proton (Failed)
          4 - benchRT_carbon (Failed)
          5 - benchImaging_ct (Failed)
          7 - benchImaging_spect (Failed)
Errors while running CTest
make: *** [Makefile:149: test] Error 8

**When I run the program I get an error as follow**

WARNING: Scene "none" not found.
  /vis/scene/list to see scenes.

### ===  Deexcitation model UAtomDeexcitation is activated for 2 regions:
          DefaultRegionForTheWorld  1  1  1
          target  1  1  1
### ===  Ignore cuts flag:   1
WARNING: command "/vis/viewer/update" could not be applied: no current viewer.

**Then I open the Viewer, /vis/open OGLSX and /vis/open OGLSQt

But no matter what command I type, nothing happens on the graphical interface. It's just black.
If you can answer my questions, I will be very grateful to you.**

**Comment by dsarrut** [comment]
Hello, 
the visualisation was not enabled for the test. The benchmarks are currently being refactored. 
thanks
David
