### ISSUE TITLE
Phase space actor: Option `enablePDGCode` not available

### ISSUE THREAD

**Issue by DavidLeibold** [OpenGATE/Gate#413]
Hello,

I wanted to enable the PDG output option for the phase space actor, as I have seen this option appear in the `GatePhaseSpaceActor.cc` and `PhaseSpaceActorMessenger.cc` source files. However, when I defined a phase space actor and added the following line

    /gate/actor/MyActor/enablePDGCode 

then this threw the following error:

    ***** Illegal parameter (0) </gate/actor/MyActor/enablePDGCode> *****
    [Gate] Sorry, error in a macro command : abort.

And when adding a `true`/`false`

    /gate/actor/MyActor/enablePDGCode   true

then the error was

    terminate called after throwing an instance of 'std::out_of_range'
      what():  _Map_base::at
    Aborted (core dumped)

Is this a bug or is this output option just not implemented?

Please let me know in case you would like to have a minimal working example.

**Comment by dsarrut** [comment]
Hello, it works for me. Can you try with the last version from the develop branch please ?

**Comment by dsarrut** [comment]
Hello @DavidLeibold, did you check with version 9.1 ? 
thanks

**Comment by DavidLeibold** [comment]
Hi @dsarrut , I'm really sorry that I haven't tested it yet. I haven't moved to version 9.1 yet, but as soon as I do, I will test it.

**Comment by dsarrut** [comment]
Hi @DavidLeibold, did you manage to test it? Thanks!

**Comment by DavidLeibold** [comment]
Hi @dsarrut, my sincerest apologies for not getting back to you earlier. After I managed to install Gate v9.1 and tested the above mentioned function, it works for me now as well.

**Comment by dsarrut** [comment]
no problem ;) thanks !
David
