### ISSUE TITLE
Make documentation of previous version of GATE available 

### ISSUE THREAD

**Issue by m-dupont** [OpenGATE/Gate#444]
At https://opengate.readthedocs.io/en/latest/, we have just access to the last version of the documentation, so the one written in the develop branch (i suppose if documentation is rebuild after each commit). 

I  think, it would be useful to have also access to the documentation of _develop branch_, 9.1, 9.0 (and if possible of 8.2). A lot of people use a specific version of GATE, and the access to doc is not straightforward.

**Comment by tbaudier** [comment]
Thank you for your comment, I activated the version 9.1 and 9.0. The version 8.2 does not provide documentation with readthedoc
