### ISSUE TITLE
(In)compatibility with Qt5

### ISSUE THREAD

**Issue by mojca** [OpenGATE/Gate#45]
I'm experiencing some problems (including crashing) when building Geant4 and Gate against Qt5, at least on Mac. For example:
![gate-with-qt5](https://cloud.githubusercontent.com/assets/15606/10326992/6cdd8742-6ca2-11e5-965a-9d17689ec313.png)
It would be nice to do some more testing and debugging of Gate against Qt5 and possibly report any problems in Geant4 upstream.

**Comment by dsarrut** [comment]
Hello, I think current develop branch version should work with qt5. Could you check on your side please @mojca ?
