### ISSUE TITLE
Voxelized phantoms with ImageNestedParametrisedVolume navigator not working with exemplary materials db

### ISSUE THREAD

**Issue by cpommranz** [OpenGATE/Gate#452]
Voxelized phantoms using the ImageNestedParametrisedVolume navigator don't work with the exemplary GateMaterials.db shipped with Gate. Logs: "GateMaterialDatabase: could not find the definition for material 'Air' in material files".

The "Air" material was removed in PR #391, but the ImageNestedParametrisedVolume navigator still needs the Air material for initialization: https://github.com/OpenGATE/Gate/blob/86083caae3a4f41903b3d1e3c3d5571e807e041e/source/geometry/src/GateImageNestedParametrisation.cc#L33

We should adapt and update the code to use G4_AIR instead.
While we are at it: A quick grep for other similar cases in the Gate code would be nice.

**Comment by dsarrut** [comment]
Thanks ! First trial: see #453

**Comment by cpommranz** [comment]
Thanks for the PR David! The changes look good to me.
