### ISSUE TITLE
How to convert MHD files to dicom RTDOSE?

### ISSUE THREAD

**Issue by carlosqueiroz** [OpenGATE/Gate#466]
In the documentation, comments on using  [__vv__](https://opengate.readthedocs.io/en/latest/tools_to_interact_with_the_simulation_actors.html#save-output) for conversion. I was unsuccessful converting mhd to dicom using vv as it requires a dicom template.

The https://github.com/OpenGATE/GateTools has the function __gt_write_dicom__ with it can I convert mhd to dicom RTDOSE?

What is the best way to convert mhd to dicom rtdose? Does anyone have an example?

**Comment by tbaudier** [comment]
Hi,
RTDose is very special and we do not have tool with gatetools to do it. You can find a tool with vv called clitkImage2DicomDose (https://github.com/open-vv/vv/blob/master/clitk_tools.md) but at least you will need a dicom template.
