### ISSUE TITLE
GATE material pressure ?

### ISSUE THREAD

**Issue by huangch18** [OpenGATE/Gate#468]
- Can "pressure" in a space be defined in GATE software?

- As can be seen in Table 2.1 of the specification, GATE contains units of air pressure, such as newton, pascal, bar, atmosphere.

- If so, how should it be done?

- Best wish!

- C. Huang

**Comment by dsarrut** [comment]
Pressure is handled by Geant4 ([see here for example](https://geant4-userdoc.web.cern.ch/UsersGuides/ForApplicationDeveloper/html/Detector/material.html?highlight=pressure)) and seems to be handled [also by GATE](https://github.com/OpenGATE/Gate/blob/86083caae3a4f41903b3d1e3c3d5571e807e041e/source/geometry/src/GateMDBFieldReader.cc#L105). 

I admit I never used this, you can try to add "p" in the description of a material in the db, like : 
`Blood:  d=1.06 g/cm3 ; n=11 ; p = 2 atm
`
But I don't really know if it works nor how you can check ;) 
Let us know ! 
David

**Comment by LZUHuang** [comment]
> * Can "pressure" in a space be defined in GATE software?
> * As can be seen in Table 2.1 of the specification, GATE contains units of air pressure, such as newton, pascal, bar, atmosphere.
> * If so, how should it be done?
> * Best wish!
> * C. Huang
