### ISSUE TITLE
ignoring return value in GateMergeManager.cc:346

### ISSUE THREAD

**Issue by olahaye74** [OpenGATE/Gate#471]
Fail to build GateMergeManager using -Wunused-result

Compiling GateMergeManager.cc...
./src/GateMergeManager.cc: In member function 'void GateMergeManager::StartCleaning(std::string, bool)':
./src/GateMergeManager.cc:346:12: warning: ignoring return value of 'int system(const char*)', declared with attribute warn_unused_result [-Wunused-result]
      system(rmfiles.c_str());
      ~~~~~~^~~~~~~~~~~~~~~~~

**Comment by dsarrut** [comment]
Done #487
