### ISSUE TITLE
gaga phsp doesn't work with the last commit

### ISSUE THREAD

**Issue by uhqd** [OpenGATE/Gate#472]
**Describe the bug**

Hello
When I try to execute a simple macro using gaga phsp 
[https://github.com/uhqd/GAMMORA/tree/main/my_first_GATE_macro](https://github.com/uhqd/GAMMORA/tree/main/my_first_GATE_macro)

It doesn't work with the last gate commit. Please notice that it works fine with the release Gate 9.1

At the end I have an error message (I am sorry I didn't copy it but it is about finding a key in json file).

I installed geant4.10.7.2 and libtorch 1.4.0

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.4, OS 11.3]
 - Gate version or commit hash: [e.g. v9.1, vGate, fa29532]
 - Geant4 version: [e.g. 10.7]
 - Root version: [e.g. v6-34-00]
 - compiler version: [e.g. clang 12.0.5, gcc 7.5.0]

**Minimal example**
*main.mac*:
```bash
```

**Expected behavior**

**Additional context**

**Comment by dsarrut** [comment]
gaga code changed ... Please check with the updated version (both Gate and gaga)
