### ISSUE TITLE
Problems compiling GATE with Root6

### ISSUE THREAD

**Issue by sylviankahane** [OpenGATE/Gate#474]
I have Root6 installed:
Welcome to ROOT 6.24/06 ...

I put -std=c++17 in all the flags.make files.

I am getting a lot of the following error:

[  5%] Building CXX object CMakeFiles/GateLib.dir/source/arf/src/GateARFDataToRoot.cc.o
In file included from /usr/local/include/TString.h:29,
                 from /usr/local/include/TNamed.h:26,
                 from /usr/local/include/TDirectory.h:24,
                 from /usr/local/include/TROOT.h:28,
                 from /home/sylvian/Gate/source/arf/include/GateARFDataToRoot.hh:15,
                 from /home/sylvian/Gate/source/arf/src/GateARFDataToRoot.cc:13:
/usr/local/include/ROOT/RStringView.hxx:32:10: error: conflicting declaration of template ‘template<class _CharT, class _Traits> using basic_string_view = std::experimental::fundamentals_v1::basic_string_view<_CharT, _Traits>’
   32 |    using basic_string_view = ::std::experimental::basic_string_view<_CharT,_Traits>;
      |          ^~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/basic_string.h:48,
                 from /usr/include/c++/11/string:55,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/istream:38,
                 from /usr/include/c++/11/sstream:38,
                 from /usr/include/c++/11/complex:45,
                 from /opt/geant4/10.7.2/include/Geant4/G4Types.hh:74,
                 from /opt/geant4/10.7.2/include/Geant4/G4ios.hh:35,
                 from /opt/geant4/10.7.2/include/Geant4/globals.hh:35,
                 from /home/sylvian/Gate/source/digits_hits/include/GateVOutputModule.hh:16,
                 from /home/sylvian/Gate/source/arf/include/GateARFDataToRoot.hh:13,
                 from /home/sylvian/Gate/source/arf/src/GateARFDataToRoot.cc:13:
/usr/include/c++/11/string_view:98:11: note: previous declaration ‘template<class _CharT, class _Traits> class std::basic_string_view’
   98 |     class basic_string_view
      |           ^~~~~~~~~~~~~~~~~

and some other stuff:

In file included from /usr/include/c++/11/bits/shared_ptr_base.h:62,
                 from /usr/include/c++/11/bits/shared_ptr.h:53,
                 from /usr/include/c++/11/memory:77,
                 from /usr/local/include/ROOT/TypeTraits.hxx:15,
                 from /usr/local/include/TString.h:30,
                 from /usr/local/include/TNamed.h:26,
                 from /usr/local/include/TDirectory.h:24,
                 from /usr/local/include/TROOT.h:28,
                 from /home/sylvian/Gate/source/arf/include/GateARFDataToRoot.hh:15,
                 from /home/sylvian/Gate/source/arf/src/GateARFDataToRoot.cc:13:
/usr/include/c++/11/ext/concurrence.h:53:16: error: ‘_Lock_policy’ does not name a type
   53 |   static const _Lock_policy __default_lock_policy =
      |                ^~~~~~~~~~~~
In file included from /usr/include/c++/11/complex:41,
                 from /opt/geant4/10.7.2/include/Geant4/G4Types.hh:74,
                 from /opt/geant4/10.7.2/include/Geant4/G4ios.hh:35,
                 from /opt/geant4/10.7.2/include/Geant4/globals.hh:35,
                 from /home/sylvian/Gate/source/digits_hits/include/GateVOutputModule.hh:16,
                 from /home/sylvian/Gate/source/arf/include/GateARFDataToRoot.hh:13,
                 from /home/sylvian/Gate/source/arf/src/GateARFDataToRoot.cc:13:
/usr/include/c++/11/ext/concurrence.h: In function ‘void std::__throw_concurrence_lock_error()’:
/usr/include/c++/11/ext/concurrence.h:99:5: error: ‘__concurrence_lock_error’ was not declared in this scope; did you mean ‘__gnu_cxx::__concurrence_lock_error’?
   99 |   { _GLIBCXX_THROW_OR_ABORT(__concurrence_lock_error()); }
      |     ^~~~~~~~~~~~~~~~~~~~~~~

In file included from /usr/include/c++/11/bits/shared_ptr_base.h:62,
                 from /usr/include/c++/11/bits/shared_ptr.h:53,
                 from /usr/include/c++/11/memory:77,
                 from /usr/local/include/ROOT/TypeTraits.hxx:15,
                 from /usr/local/include/TString.h:30,
                 from /usr/local/include/TNamed.h:26,
                 from /usr/local/include/TDirectory.h:24,
                 from /usr/local/include/TROOT.h:28,
                 from /home/sylvian/Gate/source/arf/include/GateARFDataToRoot.hh:15,
                 from /home/sylvian/Gate/source/arf/src/GateARFDataToRoot.cc:13:
/usr/include/c++/11/ext/concurrence.h:64:9: note: ‘__gnu_cxx::__concurrence_lock_error’ declared here
   64 |   class __concurrence_lock_error : public std::exception
      |         ^~~~~~~~~~~~~~~~~~~~~~~~

**Desktop (please complete the following information):**
 - OS: [e.g. kali-linux 2021.4]
 - Gate version or commit hash: [latest one cloned from GitHub]
 - Geant4 version: [e.g. 10.7.2]
 - Root version: [e.g. v6.24/06]
 - compiler version: [gcc version 11.2.0 (Debian 11.2.0-10) ]

**Comment by tbaudier** [comment]
Hello @sylviankahane 

I encountered a similar problem to compile Gate on the new Github action platforms.
Maybe you can find a solution in that PR:
https://github.com/OpenGATE/Gate/pull/477
