### ISSUE TITLE
Rayleigh data are not available in G4EMLOW8.0

### ISSUE THREAD

**Issue by tbaudier** [OpenGATE/Gate#492]
**Describe the bug**
With Geant4 v11.0, we need to use G4EMLOW v.8.0. But with these data version, we cannot found G4EMLOW8.0/rayl folder. Another folder is present in G4EMLOW8.0/livermore/rayl
With version 7.13 of G4EMLOW, rayl and livermore/rayl were present both but they were not identical.

So I do not know if we need to change the path to livermore/rayl

**Desktop (please complete the following information):**
 - OS: all
 - Gate version or commit hash: latest commit
 - Geant4 version: **11.0**
 - Root version: all
 - compiler version: all

**Minimal example**
The data are used 3 times:
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateFixedForcedDetectionFunctors.hh#L787
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateFixedForcedDetectionFunctors.hh#L791
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/src/GateDiffCrossSectionActor.cc#L168

**Additional context**
cc @SimonRit

**Comment by tbaudier** [comment]
I post an issue on the topic of Geant4:
https://geant4-forum.web.cern.ch/t/rayl-folder-in-g4emlow8-0/7302

**Comment by SimonRit** [comment]
Thanks @tbaudier. If I remember correctly, the FixedForcedDetection actor was developed to mimick [G4LivermoreRayleighModel](https://gitlab.cern.ch/geant4/geant4/-/blob/b1eb5424d2e561eed732e8a9b976b16e7f281856/source/processes/electromagnetic/lowenergy/src/G4LivermoreRayleighModel.cc). See for example [this Geant4 code](https://gitlab.cern.ch/geant4/geant4/-/blob/b1eb5424d2e561eed732e8a9b976b16e7f281856/source/processes/electromagnetic/lowenergy/src/G4LivermoreRayleighModel.cc#L105-L115) and [this Gate code](https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/include/GateFixedForcedDetectionFunctors.hh#L785-L792). The DiffCrossSectionActor was used for developing this. The G4LivermoreRayleighModel was significantly modified in the following Geant4 versions, e.g. with the use of the G4RayleighAngularGenerator to sample directions. The G4LivermorePolarizedRayleighModel still seem to use the old approach. I'm not sure what is the best way forward, there is no straightforward patch.

**Comment by SimonRit** [comment]
@jmletang

**Comment by jmletang** [comment]
Yes, the new files "re-cs-Z.dat" and "re-ff-Z.dat" are almost the same. Before the data-reading method [LoadData()](https://gitlab.cern.ch/geant4/geant4/-/blob/b1eb5424d2e561eed732e8a9b976b16e7f281856/source/processes/electromagnetic/pii/src/G4DataSet.cc#:~:text=G4bool%20G4DataSet%3A%3ALoadData(const%20G4String%26%20fileName)) was used. It assumed no header lines and two "-1 -2" lines at the end. Now the new Rayleigh files in Livermore have the same data but there is a 2 ascii-line header coding the number of entry lines and no "-1 -2" lines at the end of the file. The new data-reading method is now [Retrieve()](https://gitlab.cern.ch/geant4/geant4/-/blob/b1eb5424d2e561eed732e8a9b976b16e7f281856/source/global/management/src/G4DataVector.cc#:~:text=G4bool%20G4DataVector%3A%3ARetrieve(std%3A%3Aifstream%26%20fIn%2C%20G4bool%20ascii)). The patch is indeed not straighforward although the data format itself did not really changed.
