### ISSUE TITLE
Compilation in 32bits may fail.

### ISSUE THREAD

**Issue by YPatois** [OpenGATE/Gate#52]
Hi,

Compilation in 32 bits can fail on 32 bits at:
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/src/GateMaterialMuHandler.cc#L389

modelPE = (dynamic_cast<G4VEmProcess *>((*processListForGamma)[i]))->SelectModelForMaterial(incidentEnergy, physicRegionNumber);
As:
G4VEmModel* G4VEmProcess::SelectModelForMaterial(G4double, size_t&) const

but:
long unsigned int physicRegionNumber = 0;

On 32bits platform, size_t can be "unsigned 32bits int", and a reference to long unsigned int in 64bits cand be cast to it, so breaking the code.

Thanks.

Yannick

**Comment by dsarrut** [comment]
Thank you to report Yannick. Could you propose a fix please ?

**Comment by YPatois** [comment]
Hi,

The obvious would be to replace at
https://github.com/OpenGATE/Gate/blob/develop/source/digits_hits/src/GateMaterialMuHandler.cc#L386
	long unsigned int physicRegionNumber = 0;
by:
        size_t physicRegionNumber = 0;

In that case, it will always be coherent with the definition of G4VEmModel G4VEmProcess::SelectModelForMaterial(G4double, size_t&) const, whatever the local plateform definition of size_t.

That's what I did to compile it on 32b.

Is that fine for you?

**Comment by dsarrut** [comment]
sorry for the delay (I was traveling) ... Yes it's fine ! 
Could you please propose a pull_request ? (it is a bit heavy for this simple change, but it allows to insert you as an author ;)
Thanks !

**Comment by mojca** [comment]
David, you can use the following variables:
`````
export GIT_COMMITTER_NAME="Name"
export GIT_AUTHOR_NAME="Name"
export GIT_COMMITTER_EMAIL="<email>"
export GIT_AUTHOR_EMAIL="<email>"
`````
If you set just `GIT_AUTHOR_...`, it will keep your name as committer; if you set both, your name will be invisible on commit. Maybe even something like
`````
git commit --author "Author Name <email@address.com>"
`````
works. I haven't tested the latter.

**Comment by dsarrut** [comment]
ok, done as suggested !
