### ISSUE TITLE
Install Gate9.2 error

### ISSUE THREAD

**Issue by lvll98** [OpenGATE/Gate#529]
**Describe the bug**
When I installed the Gate9.2, I met a error:"
CMake Error at CMakeLists.txt:134 (MESSAGE):
  ROOT has been compiled with cxx_std_11, please use cxx_std_17 as your
  Geant4."

**Desktop (please complete the following information):**
 - OS: [Centos7]
 - Gate version or commit hash: [e.g. v9.2]
 - Geant4 version: [e.g. 11.0.1]
 - Root version: [e.g. v6-24-06]
 - compiler version: [e.g. clang 12.0.5, gcc 7.5.0]

I can't solve it.

**Comment by tbaudier** [comment]
Hi @lvll98 

Before the compilation of root, activate the following flag during the ccmake step:
CMAKE_CXX_STANDARD = 17

**Comment by lvll98** [comment]
Thank you for your reply. It's worked. Thank you for your help.
