### ISSUE TITLE
GATE should refuse to be built with MT geant4 installations

### ISSUE THREAD

**Issue by djboersma** [OpenGATE/Gate#53]
As illustrated by a recent discussion on gate-users [1], Gate is not designed to work correctly with MT geant4. In order to avoid unpleasant surprises I think it would be good if the build system tries to detect whether geant4 is MT or sequential, and throws an error in case of MT geant4. Documentation (wiki/README) needs to highlight this as well.

I might have some time to work on this issue later this week.

[1] http://article.gmane.org/gmane.comp.science.opengate.user/5356

**Comment by BishopWolf** [comment]
As you may see I have been working on a MT capable version of GATE, unsuccessfully until now :( But this requires that GATE shall be allowed to detect MT capabilities of Geant4. On the other hand I doesnt receive much help but i was stucked in geometry construction at MT, something geant4 doesnt like from current geometry construction from gate. I have this branch discontinued for a while so i am thinking of restarting the job there, maybe some more entusiast could help ;) https://github.com/BishopWolf/Gate

**Comment by dsarrut** [comment]
Sure ! For the moment, a MT version of GATE is not planned. As Alex said, it is not easy. 

DavidB, If you can propose a pull-request that ensure that Gate is linked to a non-MT G4 version, it would be really useful !

**Comment by djboersma** [comment]
Hi DavidS,

I think I can do that. I found the Geant4 cmake variable that says whether Geant4 is MT or not, and I guess I can just add an if statement in CMakeLists.txt that checks this variable and throws a failure in case it's ON. I want to test this with a few different Geant4 installations before I submit the pull request.

Apart from this simple brute force solution I have been thinking about alternatives. I wonder if it is possible to instruct MT Geant4 to run strictly in single thread mode, even if more cores are available. Maybe there is a compile-time or link-time flag that would accomplish this, or maybe a run-time function call. Then we still need to ensure that random number seeding works like it used to work with non-MT geant4.
https://twiki.cern.ch/twiki/bin/view/Geant4/Geant4MTTipsAndTricks#11_How_are_exactly_random_number

It would be cool and convenient if Gate could work correctly with MT geant4. It would put fewer restrictions on the user system. Some cluster admins (like here in Sweden) are really encouraging users to run multi-core processes, instead of running many more single core processes. But I am having trouble to debunk a cynical objection that keeps popping up in my mind: is it really much more efficient to run a single multithreaded program on a multicore machine instead of single-threaded versions of that program on each of the cores? Of course there is some extra overhead from those multiple instances of single-threaded programs, but that might be a low price to pay (just add a bit more RAM) for the relative simplicity and robustness that comes with single threaded programming. As I mentioned earlier, I'm a newbie in MT programming, but from what I've read about it I think that MT programming is hard, it's very nontrivial to ensure that the different threads are not screwing up each other's state and if one thread crashes then it might take down all the others with it, resulting in a much bigger loss of CPU time than when a single threaded program crashes. I do not really like these arguments, it would be really nice if someone could convincingly show me why they are wrong.

**Comment by BishopWolf** [comment]
Dear DavidB

Your perception of MT applications is wrong, a MT version of gate must share one geometry for all threads, while multiple single thread instances of it have each own geometry. In terms of RAM i can say one of my geometries get up to 1GB RAM alone. so to have 8 single thread i will need 8gb ram at least while on a MT version I would still need 1gb for that. Scale that to a Phi coprocessor with 72 cores and you will see what i mean.

**Comment by djboersma** [comment]
Well, yes, that is actually precisely what I meant with "some extra overhead" for multiple instances of single threaded programs. And 8 GiB RAM is not that much, compared to a week salary for a researcher. I did not yet think of a Phi coprocessor. But the cynical evil voice in my head claims that you can buy large RAM chips (128 GiB), which are expensive, but so is a Phi coprocessor, and they are less expensive for an employer than paying a researcher's monthly salary (including taxes).

Is the geometry construction really the only obstacle to make Gate MT compliant? Which other Gate subsystems did you already fix (I guess I should check the changelog of your branch)? I would think that basically *all* Gate code needs to be reviewed & fixed for thread safety. That is an awful lot of code. From the Geant4 twiki I gathered that there is some automatic static analysis code conversion tool to convert existing Geant4 applications to the new MT paradigm, but the user still needs to check *all* changes that it does to the application code, because sometimes it does surprising things (according to a FAQ on that same twiki).

**Comment by djboersma** [comment]
Pull request (#56) has been submitted. By default it throws a fatal error for MT geant4, but it allows you to do MT Gate development by setting the GATE_ALLOW_MT_GEANT4 option to ON.

**Comment by BishopWolf** [comment]
Ok thanks for leaving the option to develop the MT GATE ;)

Regarding RAM overloading I can show a practical example of 10GB per thread if you want, so i can prove memory treatment is not a question of how large your pocket is, also you need to handle with transfer speed and other stuffs that are very unefficient with single threads apps. I think it is mandatory to release an MT version of gate in the very near future. As I proposed, a working group shall be created for this purpose and version 8 of Gate shall have this as milestone!!

**Comment by dsarrut** [comment]
Interesting discussion ! For now, Gate MT has not been planned. It is still not yet clear if it worth the (high) effort. Most people just split simulations by launching several Gate jobs (at the expense of memory increase).

**Comment by dsarrut** [comment]
(I close the discussion because the patch is integrated )
