### ISSUE TITLE
Optical surface direction problem

### ISSUE THREAD

**Issue by woolaman** [OpenGATE/Gate#543]
Dear GATE users,
    I suspect that the optical surface definition is incorrect in the GATE documentation sample code:
    /gate/Volume2/surfaces/name         Surface-From-Volume1-To-Volume2
    /gate/Volume2/surfaces/insert         Volume1
    /gate/Volume2/surfaces/Surface-From-Volume1-To-Volume2/SetSurface  Surface_name

In my code, I set:
![image](https://user-images.githubusercontent.com/8493107/181482167-f2d1ef31-0f5b-4061-aa6e-aca0b9108aae.png)

I can see many lights are reflected in the light guide volume(left part), and a small number of lights transmit to the SiPM volume(right part).
![image](https://user-images.githubusercontent.com/8493107/181482308-31a3f94b-a8a8-48f2-bf22-ace1d6902c34.png)

when I modify the code as below, then no lights are reflected.
![image](https://user-images.githubusercontent.com/8493107/181482408-2339bb1b-6aaa-43dc-aa2d-9da1a386ed53.png)
![image](https://user-images.githubusercontent.com/8493107/181482656-5efeeeac-daf7-49f9-b4b8-122d9d93b5ab.png)

So I think that the sample code is setting the surface from volume2 to volume1, not volume1-->volume2.
    /gate/Volume2/surfaces/name         Surface-From-Volume1-To-Volume2
    /gate/Volume2/surfaces/insert         Volume1
    /gate/Volume2/surfaces/Surface-From-Volume1-To-Volume2/SetSurface  Surface_name

If I'm right, please revise the GATE documentation.

**Comment by thilomasbaum** [comment]
I second this, after making some trials myself!
