### ISSUE TITLE
Add phantoms into voxelized phantoms and calculate dose distributions

### ISSUE THREAD

**Issue by tyxiong123** [OpenGATE/Gate#550]
Hi,
I try to calculate dose distributions for seed implant brachytherapy. I firstly imported CT files to construct a voxelized patient phantom using regionalized parameterization method. And then a few I-125 seed models were placed into the voxelized patient phantom. I used DoseActor which was attached to the voxelized patient phantom to record dose distributions. However, results showed that seed models did not influence dose distributions. Is there any way of implanting phantoms into voxelized phantoms and recording correct dose distributions?

**Comment by dsarrut** [comment]
Hi, 
please have a look at https://github.com/OpenGATE/GateBenchmarks/tree/master/t22_merged_actor it may help
@JulienBert

**Comment by tyxiong123** [comment]
Thanks for your help! I tried and it worked.

**Comment by dsarrut** [comment]
great ;) !
