### ISSUE TITLE
vGate 9.2 Enter the command and the message "Not Found" is displayed.

### ISSUE THREAD

**Issue by yuxiXo** [OpenGATE/Gate#552]
**Describe the bug**
I am a beginner and follow the instructions of the tutorial step by step, but after entering a lot of instructions will prompt "not found"

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.4, OS 11.3]
 - Gate version or commit hash: [e.g. v9.2, vGate, fa29532]
 - Geant4 version: [e.g. 11.0]
 - Root version: [e.g. v6-34-00]
 - compiler version: [e.g. clang 12.0.5, gcc 7.5.0]

**Minimal example**

**Expected behavior**

**Additional context**

**Comment by dsarrut** [comment]
I am sorry, we dont have enough information to reply.
