### ISSUE TITLE
Visualization in DOCKER

### ISSUE THREAD

**Issue by ignacio-scarinci** [OpenGATE/Gate#553]
Hello, the docker version does not allow to use of the visualization. I was looking for a solution to this problem, and I was able to solve it by simply adding the following line in the DockerFileGeant file:
mesa-dri-drivers

```
RUN yum install -y make
                    libX11-devel.x86_64 \
                    libXpm-devel.x86_64 \
                    libXft-devel.x86_64 \
                    libXext-devel.x86_64 \
                    libXmu-devel.x86_64 \
                    libxml2-devel.x86_64 \
                    binutils \
                    qt5-qtbase-devel.x86_64 \
                    git \
                    cmake \
                    wget \
                    mesa-libGLU-devel.x86_64 \ 
                    python3-devel \
                    python3-devel \
                    which nano \
                    mesa-dri-drivers
```

I think that in the following versions, this could be added to be able to have the possibility to use visualization.

Regards

**Comment by BishopWolf** [comment]
Please, add the changes yourself. You know this is a collaborative work! ;)

**Comment by dsarrut** [comment]
Thanks, Ignacio, we will have a look!

**Comment by BishopWolf** [comment]
The PR has been merged. This topic may be closed @dsarrut . 
Thanks @ignacio-scarinci

**Comment by dsarrut** [comment]
thanks !
