### ISSUE TITLE
Problem in Gate Visual

### ISSUE THREAD

**Issue by msarvi** [OpenGATE/Gate#572]
**Describe the bug**
Dear Friend's. when run the code blow, the world geometry created in visual but the phantom is not. but when i use "`/gate/geometry/listVolumes`" the Phantom is available. please guide me. i used "`/gate/geometry/rebuild`" and "`/gate/run/initialize`" but nothing changed.
### Visual ###
```
#/vis/open OGLSQt
/vis/open OGLSX
/vis/viewer/reset
/vis/drawVolume
/vis/scene/add/trajectories

/vis/viewer/set/viewpointThetaPhi 45 45

/vis/viewer/zoom 1

/vis/viewer/set/style surface
/vis/scene/endOfEventAction accumulate 100000000
/vis/viewer/update
/vis/viewer/refresh
/vis/scene/add/axes 
```

### Define Material DB ###
`/gate/geometry/setMaterialDatabase ../GateMaterials.db`

### World ###
```
/gate/world/geometry/setXLength 100. cm
/gate/world/geometry/setYLength 100. cm
/gate/world/geometry/setZLength 100. cm
/gate/world/setMaterial Air
/gate/world/vis/forceWireframe
/gate/world/vis/setColor white

/gate/world/daughters/name Phantom
/gate/world/daughters/insert box
/gate/Phantom/placement/setTranslation 0 10 0 cm


/gate/Phantom/geometry/setXLength 20. cm
/gate/Phantom/geometry/setYLength 10. cm
/gate/Phantom/geometry/setZLength 10 cm
/gate/Phantom/setMaterial Water
/gate/Phantom/vis/setColor blue
/gate/Phantom/vis/forceWireframe
/gate/Phantom/enable
```
### Result ###
![Screenshot from 2023-02-11 17-39-51](https://user-images.githubusercontent.com/48852674/218269928-1dfcc1ef-44c7-40ee-bda2-88c6412e4de2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.4, OS 11.3]
 - Gate version or commit hash: [e.g. v9.2, Gate, fa29532]

**Minimal example**
*main.mac*:
```bash
```

**Expected behavior**
all the Volumes must show in Visual

**Comment by tbaudier** [comment]
Hi @msarvi 

Do you set the visualisation after the initialization? eg:

```
#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#=====================================================
# VISUALISATION
#=====================================================

##/vis/disable

/vis/open                           OGLSX
/vis/viewer/set/viewpointThetaPhi   60 60
/vis/viewer/zoom                    6.0
/vis/drawVolume
/tracking/storeTrajectory           1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction         accumulate

/control/execute                    Verbose.mac

```
