### ISSUE TITLE
vGate9.0 1.no hits in root 2.double singles output 3.memory leak!(2Mb/s along the simulation time)

### ISSUE THREAD

**Issue by jxhno1** [OpenGATE/Gate#574]
![image](https://user-images.githubusercontent.com/37684984/218899618-ce4b175a-00a2-4c31-b281-f67ced2c7320.png)
![image](https://user-images.githubusercontent.com/37684984/218899908-e231b1e6-eef8-46ab-b5a0-3b0a81249d24.png)

**Comment by NikEfth** [comment]
I confirm the bug. The memory leak is quite severe.

**Comment by kochebina** [comment]
Dear @NikEfth and @jxhno1,

Could you share your full macros which give the memory leak, please ?

Cheers,
Olga

**Comment by jxhno1** [comment]
I did not know which file lead that, but I can send your files later



| |
jxhzk1314
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 05/12/2023 15:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [OpenGATE/Gate] vGate9.0 1.no hits in root 2.double singles output 3.memory leak!(2Mb/s along the simulation time) (Issue #574) |

Dear @NikEfth and @jxhno1,

Could you share your full macros which give the memory leak, please ?

Cheers,
Olga

**Comment by cpommranz** [comment]
The empty Hits tree and the memory leak seen in GATE v9.0 were fixed with PR #354 and #357 and the issues were resolved in GATE v9.1 and above. If you need to stay with GATE v9.0 you could try to apply the commits from the pull requests.

**Comment by NikEfth** [comment]
Hi, I was away for a few weeks. 
The memory leak is present in the developer branch. 
I am using the new digitizer commands, but I don't know which command creates it.

**Comment by tontyoutoure** [comment]
Yes, although #639 is about something else, but I also observed mem leak in the mean time. Didn't notice this things is related.
