### ISSUE TITLE
Does docker Gate9.2 enable GPU? How could I accelerate simulation?

### ISSUE THREAD

**Issue by yllgl** [OpenGATE/Gate#581]
Now I have used vGate9.2 on Windows 10. But I found it was too slow when I simulate a duration of 10 seconds with 50 million events. It almost takes me two days. How could I accelerate this process? I can use Linux with docker but I don't know if it would use GPU to accelerate. Or  I must compile it from scratch by myself?

**Comment by tbaudier** [comment]
Geant4 and Gate are not usable with GPU. Prefer to run the simulation on multiple CPU as jobs and merge them later
