### ISSUE TITLE
how i can get the efficiency of bremsstrahlung splitting with Phase space ??

### ISSUE THREAD

**Issue by Abderraouf4** [OpenGATE/Gate#588]
hello
how do i use the command of Bremsstrahlungsplitting (/gate/physics/processes/Bremsstrahlung/activateSplitting [Particle] [N]) with Phase space ,it does not work ? 
and how i can use the Splitting just in my phantom ?

**Comment by dsarrut** [comment]
Hi, 
please use the following : 
	/process/em/setSecBiasing eBrem target 100 5 MeV
which mean : x100 splitting for all e- below 5 MeV
