### ISSUE TITLE
New user, and unable to get the Docker Gate container to run.

### ISSUE THREAD

**Issue by Jmixen** [OpenGATE/Gate#589]
**Describe the bug**

I'm new to setting this software up for researchers. I'm currently trying to install Gatev9.2 via docker, and I get the error in the container. 

[G4-cerr] ERROR: Can not open a macro file <mac/main.mac>. Set macro path with "/control/macroPath" if needed.
[Gate] Sorry, error in a macro command : abort.

I see a mention of this said macro file in the docs, but other than that I am unsure of what this is asking for exactly. I can get the images from docker hub and get the geant4 container running with no issues, but the Gate container is just throwing the error above.

**Server (please complete the following information):**
 - OS: Rocky 8
 - Gate version or commit hash: docker Gate v9.2
 - Geant4 version: 11.0.0
 - Root version: 6-24-06
 - compiler version: trying to use docker.

I get the following output whether I pull the image from docker hub or I pull the repo and build the images locally and the geant4 container is running: 

[root@rad-cmijha04 apps]# docker run -it docker.io/opengatecollaboration/gate:9.2-docker

          ################################
          !!! G4Backtrace is activated !!!
          ################################

[G4]
[G4] **************************************************************
[G4]  Geant4 version Name: geant4-11-00    (10-December-2021)
[G4]                        Copyright : Geant4 Collaboration
[G4]                       References : NIM A 506 (2003), 250-303
[G4]                                  : IEEE-TNS 53 (2006), 270-278
[G4]                                  : NIM A 835 (2016), 186-225
[G4]                              WWW : http://geant4.org/
[G4] **************************************************************
[G4]
[Core-0] Initialization of geometry
[Core-0] Initialization of physics
[Core-0] Initialization of actors
[Core-0]
[Core-0] *******************************************************
[Core-0]  GATE version 9.2 (2022)
[Core-0]  Copyright : OpenGATE Collaboration
[Core-0]  Reference : Phys. Med. Biol. 49(19) 4543-4561     2004
[Core-0]  Reference : Phys. Med. Biol. 56(4)  881-901       2011
[Core-0]  Reference : Med. Phys.       41(6)  1-14          2014
[Core-0]  Reference : Phys. Med. Biol. 66(10) 1-23          2021
[Core-0]  http://www.opengatecollaboration.org
[Core-0] *******************************************************
[Core-0]
[Core-0] You are using Geant4 version 11.0.0
[Core-0] Starting macro mac/main.mac
[G4-cerr] ERROR: Can not open a macro file <mac/main.mac>. Set macro path with "/control/macroPath" if needed.
[Gate] Sorry, error in a macro command : abort.

**Expected behavior**

Expect to pull docker image and container runs application configured within it.

**Additional context**
I'm an IT infrastructure engineer installing and setting this software up for the first time. So please excuse my lack of knowledge on this software.

**Comment by Jmixen** [comment]
Figured out the docker problem I had. I misunderstood the different docker run commands that where being referenced. 

Apparently I needed clarity on the following 

pull the image from docker hub > 

then run docker run -it --rm -v $PWD:/APP --entrypoint /bin/bash opengatecollaboration/gate:$version > 

exit the container >

to execute commands with that container was docker run -i --rm -v $PWD:/APP opengatecollaboration/gate:$version Gate > 

That showed me the version and that the container was working with. Sorry for my inexperience with this software, but hopefully this clears up some confusion for others in the future.

**Comment by BishopWolf** [comment]
Just for clarification: I have this in my .bash_aliases
```
alias Gate93='docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate:9.3-docker'
alias Gate92='docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate:9.2-docker'
alias Gate91='docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate:9.1-docker'
alias Gate81='docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate:8.1-docker'
alias Gate82='docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate:8.2-docker'
alias Gate90='docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate:9.0-docker'
```

So you can just run Gate93 in the directory where you have the mac folder

**Comment by Jmixen** [comment]
That's good to know, thank you @BishopWolf . Yeah I don't actually use the program itself, but I realized that I was getting stuck on the mac file. When it didn't need to be anywhere to get the container running. Apparently the mac is something that is used / created to run a project in GATE?

**Comment by BishopWolf** [comment]
Hi @Jmixen the mac folder is only required for the docker image to run as it was designed this way. In normal Gate (built from source) it is not required.

**Comment by xie-pixel** [comment]
Hello @Jmixen@BishopWolf,I am a student, ready to learn to use gate,I had the same problem with the Jmixen,my OS is ubuntu20.04,I want to use Gate through dockers, so I run this command in the terminal:docker run -ti opengatecollaboration/gate,
Results appear:Starting macro mac/main.mac
[G4-cerr] ERROR: Can not open a macro file <mac/main.mac>. Set macro path with "/control/macroPath" if needed.
[Gate] Sorry, error in a macro command : abort.
I don't know where this file is,This is the first time for me to use gate and docker, and there are many things I don't understand. Could you please give me some advice? Thank you very much

**Comment by xie-pixel** [comment]
I solved the problem by running this command:docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate /control/execute,In addition, I would like to know whether gate can output the energy of secondary particles produced after the simulated interaction between particles and matter

**Comment by xie-pixel** [comment]
Hi @Jmixen@BishopWolf,Thank you very much,I solved the problem by running this command:docker run -ti --rm -v "$PWD":/APP opengatecollaboration/gate /control/execute,In addition, I would like to know whether gate can output the energy of secondary particles produced after the simulated interaction between particles and matter,Could you please give me some advice?
