### ISSUE TITLE
Optical Data output number is wrong - only number of primaries

### ISSUE THREAD

**Issue by thilomasbaum** [OpenGATE/Gate#598]
Hi!
I'm currently working with Gate9.3 and trying out Optical Simulation with Scintillation processes.
It's working fine thus far, except when I try to generate Optical Data with:

/gate/output/root/setRootOpticalFlag 1

the ROOT Branch only contains Data Points to the number of Primaries, in contrast to the number of actual Optical Photons, which I identified are generated in the crystal using actors and the Hits Collection.

I suspect an error in looping over all optical photons, either in data aquisition or creation of output.

Thank you very much for your hard work!
Kind regards

**Comment by kochebina** [comment]
Dear @thilomasbaum,

Thanks for this finding, I'll check it in coming days.

Cheers,
Olga

**Comment by kochebina** [comment]
Dear @thilomasbaum,

From a first sight, I don't see problems in filling, so it seems that the problem is deeper and older.
Could you, please, share your macros that you use for this test? 
You could send them to me by email: kochebina [a] gmail.com

Cheers,
Olga
