### ISSUE TITLE
Could Gate be installed and compiled on Apple Silicon Mac platform？

### ISSUE THREAD

**Issue by jxaflxb** [OpenGATE/Gate#606]
in official Guide or github topics ，**there are some required dependencies which not be accessible**, may be some part of the guide is not updated in time. Also , Geant 4 v11 is working perfect on Apple Silicon Mac platform, Can Gate worked well onon Apple Silicon Mac platform?

**Comment by BishopWolf** [comment]
Hi, you can always use the docker images. Please refer to https://opengate.readthedocs.io/en/latest/docker_gate.html

As long as docker runs, you have gate running.

**Comment by dsarrut** [comment]
Hi, 
I don't have any problem with M1, what is the issue exactly? 
David

**Comment by jxaflxb** [comment]
> Hi, I don't have any problem with M1, what is the issue exactly? David
I followed the official guide, but it failed in the build part, Such as RTK. can you list the installation procedure briefly based on the offcial guide. Thank you very much.
<img width="439" alt="image" src="https://github.com/OpenGATE/Gate/assets/36333183/4fd7023e-9a8c-4a39-93e2-f8a6fa437dd6">

**Comment by dsarrut** [comment]
ITK and RTK are optional, try first with their flags set to OFF to see

**Comment by jxaflxb** [comment]
> ITK and RTK are optional, try first with their flags set to OFF to see\
Hi, after retry the process once again, maybe it refers to the  unmatched Gate 9.2 version related to  Geant4 11.1.1 version on my local mac， both available Gate version via GIt  and docker is 9.2 not 9.3.so could you provide the Gate version  9.3 files , or the  Geant4 Downgrade Process would be cumbersome again

<img width="579" alt="image" src="https://github.com/OpenGATE/Gate/assets/36333183/6ea8fe60-2bed-4231-a645-62f3949a63f5">
<img width="509" alt="image" src="https://github.com/OpenGATE/Gate/assets/36333183/371c2287-b907-4ad3-b11d-a67e9076ddc3">

**Comment by kochebina** [comment]
Dear @jxaflxb, 

Could you address your question in the gate mailing-list, please?
This subject would be more suitable there.

Cheers,
Olga
