### ISSUE TITLE
Gate command not working in vGATE v9.0

### ISSUE THREAD

**Issue by sbdrchauhan** [OpenGATE/Gate#612]
Add any 
![Screenshot from 2023-05-26 21-18-52](https://github.com/OpenGATE/Gate/assets/58833553/460eb5b6-4459-4115-bfa8-88f478b7a389)
other context about the problem here.

**Comment by sbdrchauhan** [comment]
Gate command not working to start-up gate simulation. Please help.

**Comment by tontyoutoure** [comment]
It should be installed at `$HOME/Software/Gate` directory. Maybe you can check there first?
