### ISSUE TITLE
CT imaging on a mesh model

### ISSUE THREAD

**Issue by yuxiXo** [OpenGATE/Gate#620]
Hello folks,

I am a very new user of Gate, and want to simulate CT imaging on a mesh model. The code combines GateContrib-master\imaging\CT\classic and \misc\TetrahedralMeshGeometry examples in OpenGate.
I am currently running into trouble.

 **<!> *** WARNING *** <!>  The current TetMeshBox implementation doesn't support additional child volumes.
 <!> *** WARNING *** <!>  Unknown process: MultipleScattering**

List of Enabled processes:

   ===  Process: Bremsstrahlung  ===
**Particle: e+
    * Model(s):
       - <!> *** Warning *** <!> No model selected!**
Particle: e-
    * Model(s):
       - StandardModel

   ===  Process: Compton  ===
Particle: gamma
    * Model(s):
       - PenelopeModel

   ===  Process: ElectronIonisation  ===
Particle: e+
    * Model(s):
       - <!> *** Warning *** <!> No model selected!
Particle: e-
    * Model(s):
       - StandardModel

   ===  Process: PhotoElectric  ===
Particle: gamma
    * Model(s):
       - StandardModel

   ===  Process: RayleighScattering  ===
Particle: gamma
    * Model(s):
       - PenelopeModel

List of initialized processes:

[Core-0] Initialization of geometry
I/O warning : failed to load external entity "./Materials.xml"
I/O warning: Discard the previous warning if your simulation doesn't transport OPTICAL PHOTONS.
Otherwise, please copy the ./Materials.xml file from the gate-source directory in the directory where you run your main macro.
I/O warning : failed to load external entity "./Materials.xml"
I/O warning: Discard the previous warning if your simulation doesn't transport OPTICAL PHOTONS.
Otherwise, please copy the ./Materials.xml file from the gate-source directory in the directory where you run your main macro.
[Core-0] Initialization of physics
[Physic-0] WARNING: manual physic lists are being deprecated.
Please, use physics list builder mechanism instead. Related documentation can be found at:
http://wiki.opengatecollaboration.org/index.php/Users_Guide:Setting_up_the_physics
[Core-0] Initialization of actors
/tracking/storeTrajectory 1
Attributes available for modeling and filtering with
  "/vis/modeling/trajectories/create/drawByAttribute" and
  "/vis/filtering/trajectories/create/attributeFilter" commands:
G4TrajectoriesModel:
  Event ID (EventID): G4int
  Run ID (RunID): G4int
G4Trajectory:
  Charge (Ch): unit: e+ (G4double)
  Track ID (ID): G4int
  Initial kinetic energy (IKE): G4BestUnit (G4double)
  Initial momentum magnitude (IMag): G4BestUnit (G4double)
  Initial momentum (IMom): G4BestUnit (G4ThreeVector)
  No. of points (NTP): G4int
  PDG Encoding (PDG): G4int
  Parent ID (PID): G4int
  Particle Name (PN): G4String
G4TrajectoryPoint:
  Position (Pos): G4BestUnit (G4ThreeVector)
**WARNING: Trajectory storing has been requested.  This action may be
  reversed with "/tracking/storeTrajectory 0".
WARNING: The vis manager will keep up to 10 events.**
  This may use a lot of memory.
  It may be changed with, e.g., "/vis/scene/endOfEventAction accumulate 10".
GateSourceMgr::ListSources: List of the sources in the source manager
Source --------------> xraygun
  ID                 : 0
  type               : gps
  activity (Bq)      : 350000
  startTime (s)      : 0
  time (s)           : 0
  forcedUnstable     : 0
  forcedHalfLife (s) : -0.693147
  verboseLevel       : 0
  relative to vol    : world
----------------------

[Acquisition-0]
[Acquisition-0] ============= Source initialization =============
[Acquisition-0]
[Acquisition-0] ============= Acquisition starts! =============
[Acquisition-0] Simulation start time = 0 sec
[Acquisition-0] Simulation end time   = 180 sec
[Acquisition-0] Simulation will have  = 2 run(s)

****
Number of Pixels in your detector : 262144
Number of bytes by projection : 1024 Kb
****

[Acquisition-0] Slice 0 from 0 to 90 s [slice=90 s]
=======================================================================
======                 Electromagnetic Physics Parameters      ========
=======================================================================
LPM effect enabled                                 1
Enable creation and use of sampling tables         0
Apply cuts on all EM processes                     1
Use general process                                0
Enable linear polarisation for gamma               0
Enable sampling of quantum entanglement            0
X-section factor for integral approach             0.8
Min kinetic energy for tables                      100 eV
Max kinetic energy for tables                      100 TeV
Number of bins per decade of a table               7
Verbose level                                      1
Verbose level for worker thread                    0
Bremsstrahlung energy threshold above which
  primary e+- is added to the list of secondary    100 TeV
Bremsstrahlung energy threshold above which primary
  muon/hadron is added to the list of secondary    100 TeV
Lowest triplet kinetic energy                      1 MeV
Enable sampling of gamma linear polarisation       0
5D gamma conversion model type                     0
5D gamma conversion model on isolated ion          0
Livermore data directory                           livermore
=======================================================================
======                 Ionisation Parameters                   ========
=======================================================================
Step function for e+-                              (0.2, 1 mm)
Step function for muons/hadrons                    (0.2, 0.1 mm)
Step function for light ions                       (0.2, 0.1 mm)
Step function for general ions                     (0.2, 0.1 mm)
Lowest e+e- kinetic energy                         1 keV
Lowest muon/hadron kinetic energy                  1 keV
Fluctuations of dE/dx are enabled                  1
Use ICRU90 data                                    0
Use built-in Birks satuaration                     0
Build CSDA range enabled                           0
Use cut as a final range enabled                   0
Enable angular generator interface                 0
Max kinetic energy for CSDA tables                 1 GeV
Max kinetic energy for NIEL computation            0 eV
Linear loss limit                                  0.01
Read data from file for e+e- pair production by mu 0
=======================================================================
======                 Multiple Scattering Parameters          ========
=======================================================================
Type of msc step limit algorithm for e+-           1
Type of msc step limit algorithm for muons/hadrons 0
Msc lateral displacement for e+- enabled           1
Msc lateral displacement for muons and hadrons     0
Urban msc model lateral displacement alg96         1
Range factor for msc step limit for e+-            0.04
Range factor for msc step limit for muons/hadrons  0.2
Geometry factor for msc step limitation of e+-     2.5
Safety factor for msc step limit for e+-           0.6
Skin parameter for msc step limitation of e+-      1
Lambda limit for msc step limit for e+-            1 mm
Use Mott correction for e- scattering              0
Factor used for dynamic computation of angular
  limit between single and multiple scattering     1
Fixed angular limit between single
  and multiple scattering                          3.1416 rad
Upper energy limit for e+- multiple scattering     100 MeV
Type of electron single scattering model           0
Type of nuclear form-factor                        1
Screening factor                                   1
=======================================================================
======                 Atomic Deexcitation Parameters          ========
=======================================================================
Fluorescence enabled                               1
Fluorescence Bearden data files enabled            0
Fluorescence ANSTO data files enabled              0
Auger electron cascade enabled                     0
PIXE atomic de-excitation enabled                  0
De-excitation module ignores cuts                  0
Type of PIXE cross section for hadrons             Empirical
Type of PIXE cross section for e+-                 Livermore
=======================================================================

WARNING from G4PenelopeComptonModel
Atomic de-excitation module is not instantiated, so there will not be any fluorescence/Auger emission.
Please make sure this is intended
G4PenelopeComptonModel:
LowPoint: -1, High Point: 1
Tolerance: 1e-05
**Calls: 15380, Integral: 0, Error: nan**
Number of open subintervals: 258
WARNING: the required accuracy has not been attained
G4PenelopeComptonModel:
LowPoint: -1, High Point: 1
Tolerance: 1e-05
**Calls: 15420, Integral: 0, Error: nan**
......

**Desktop (please complete the following information):

OS: [e.g. Ubuntu 20.04]
Gate version or commit hash: [v9.2]
Geant4 version: [cd 11.0.3]
Root version: [ v6-26-06]

Thank you so much in advance!

**Comment by kochebina** [comment]
Dear @yuxiXo, 
please, address this kind of questions to gate maling list: opengate-l (at) in2p3.fr
