### ISSUE TITLE
SPECT fanbeam collimator

### ISSUE THREAD

**Issue by zhaozhijun714** [OpenGATE/Gate#621]
Dear GATE users and developers,
When I was modeling the fanbeam collimator in Gate 9.2, there was an error after initialization, using the code in the Official Users Guide, can anyone tell me how to fix this?
Best wishes.

**Comment by qingshuijue6382** [comment]
Dear all, Has the problem been solved?

**Comment by kochebina** [comment]
Dear @zjZhao714 , could you, please, share your macros that make the error, please?
