### ISSUE TITLE
Problems after vGate9.3 installation

### ISSUE THREAD

**Issue by maikeros** [OpenGATE/Gate#632]
Hello there, 

I updated Gate this week from 9.2 to 9.3. I adjusted the digitizer with the converter given from Opengate. When I want to do a CT-Simulation with more than one time slice now, I get wrong results. All the runIDs are the same. There is no differentiation between the different runs anymore in the root file. Before the update everything worked out. I don't know, if it maybe has something to do with the digitizer. 

Would be so glad for your help! 

Kind regards,

Maike

**Comment by kochebina** [comment]
Dear Maike,

Normally, this issue was solved this summer. 
Do you have this issue with the last version pulled from git hub? 

Cheers,
Olga

**Comment by maikeros** [comment]
Dear Olga, 

I didn't mange to compile Gate with root etc on my own, so I finally chose to install gate9.2 again and I am working with that now. So I don't know, whether it is solved or not.

Cheers,
Maike
