### ISSUE TITLE
for pPs + prompt gamma simulation with Gate

### ISSUE THREAD

**Issue by Ermias-90** [OpenGATE/Gate#666]
I used the extended source format; it says my code is dumped when I add the excitation gamma to the source. mac.
Do you have any suggestions? I am a beginner at using Gate.

/gate/source/addSource Na22PromptGamma Extended
/gate/source/Na22PromptGamma/setType sg  
/gate/source/Na22PromptGamma/setEnableDeexcitation true
/gate/source/Na22PromptGamma/setPromptGammaEnergy 1275 keV

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : Cache001
      issued by : G4CacheReference<V>::Destroy
Internal fatal error. Invalid G4Cache size (requested id: 8 but cache has size: 6 Possibly client created G4Cache object in a thread and tried to delete it from another thread!
*** Fatal Exception *** core dump ***
[G4-cerr]  **** Track information is not available at this moment
[G4-cerr]  **** Step information is not available at this moment
[G4-cerr] 
-------- EEEE -------- G4Exception-END --------- EEEE -------

[G4-cerr] 
[G4-cerr] *** G4Exception: Aborting execution ***
Aborted (core dumped)
  
suggestions are welcomed.

**Comment by kochebina** [comment]
Hello,

Please, address this kind of questions to Gate mailing list: opengate-l[at]in2p3.fr

Kind regards,
Olga
