### ISSUE TITLE
material issue!

### ISSUE THREAD

**Issue by Tmohamma** [OpenGATE/Gate#668]
Hey,

I want to specifically use boron-10 for my research. However, when I define boron-10 as both an element and material, the simulation produces the same results as natural boron. This indicates that the simulation doesn't discriminate between natural boron and the boron-10 isotope.

How can I address this issue? I'm interested in focusing on boron-10. Please help me!

Thanks!

**Comment by kochebina** [comment]
Hello,

Please, address this kind of questions to Gate mailing list: opengate-l[at]in2p3.fr

Kind regards,
Olga
