### ISSUE TITLE
Creating a circular source in Gate

### ISSUE THREAD

**Issue by ErmiasBeyene** [OpenGATE/Gate#679]
I would like to create a circular source that is located 10 cm from the center and has a radius of 14 cm, using an extended version of the source. mac, but I could not manage it. Is there anyone who is super excellent and would like to help me?

**Comment by kochebina** [comment]
Hello,

Please, adress this kind of questions to Gate mailing list: opengate-l[at]in2p3.fr

Kind regards,
Olga
