### ISSUE TITLE
Memory Leak Issue with Lu-177 Ion Source in Gate 9.0

### ISSUE THREAD

**Issue by MuHao2022** [OpenGATE/Gate#686]
Using Gate 9.0, while using the ion source of Lu-177, when running a simulation, the RAM will increase over time. I think there may be a memory leak with the command “/gate/source/lu177/gps/ion 71 177 0 0”. This issue only appears when using the ion source of Lu-177.

**Comment by tontyoutoure** [comment]
I recommand you to update your gate version to the newest, and see if the problem persists.

**Comment by MuHao2022** [comment]
> I recommand you to update your gate version to the newest, and see if the problem persists.

thank you for your advice，I have tried it on Gate9.2,and the memory leak problem is solved
