### ISSUE TITLE
Issues with Wedge Geometry in Tungsten Slit Collimator Design in Gate 9.0

### ISSUE THREAD

**Issue by MuHao2022** [OpenGATE/Gate#687]
I am using Gate 9.0 to design a slit collimator with two wedge volumes, setting the material as tungsten. Theoretically, as the NarrowerXLength increases, the photon count on the detector behind the collimator should decrease. However, after running the simulation, I found that the photon count actually increased, which does not correspond to the expected results.
The following code is the one i used to generate the collimator.
/gate/col/daughters/name colsub
/gate/col/daughters/insert box
/gate/colsub/geometry/setXLength 29.24 mm
/gate/colsub/geometry/setYLength 8.00 mm
/gate/colsub/geometry/setZLength 140.00 mm
/gate/colsub/setMaterial Air
/gate/colsub/vis/setColor white
/gate/colsub/vis/forceSolid
/gate/colsub/vis/forceWireframe

/gate/colsub/daughters/name w1
/gate/colsub/daughters/insert wedge
/gate/w1/geometry/setXLength 14 mm
/gate/w1/geometry/setNarrowerXLength 11 mm
/gate/w1/geometry/setYLength 8.00 mm
/gate/w1/geometry/setZLength 140.00 mm
/gate/w1/setMaterial Tungsten
/gate/w1/placement/setTranslation -8.34 0 0 mm
/gate/w1/vis/setColor green
/gate/w1/vis/forceSolid

/gate/colsub/daughters/name w2
/gate/colsub/daughters/insert wedge
/gate/w2/geometry/setXLength 14 mm
/gate/w2/geometry/setNarrowerXLength 11 mm
/gate/w2/geometry/setYLength 8.00 mm
/gate/w2/geometry/setZLength 140.00 mm
/gate/w2/setMaterial Tungsten
/gate/w2/placement/setRotationAxis 0 1 0
/gate/w2/placement/setRotationAngle 180 deg
/gate/w2/placement/setTranslation 8.34 0 0 mm
/gate/w2/vis/setColor green
/gate/w2/vis/forceSolid

**Comment by kochebina** [comment]
Hello,

Please, adress this kind of questions to Gate mailing list: opengate-l[at]in2p3.fr

Kind regards,
Olga
