### ISSUE TITLE
Declaring two or more aliases with bash variables doesn't work (with temporary fix)

### ISSUE THREAD

**Issue by TomThePhysicist** [OpenGATE/Gate#69]
Currently you can't start Gate with two or more aliases without wrapping it in quotation marks.
`Gate -a '[AliasOne,ParamOne] [AliasTwo,ParamTwo]' main.mac`

But if you want to use variables in aliases this solution will not work.

**How to fix it:** quote the spaces between aliases
`Gate -a [AliasOne,$VarOne]' '[AliasTwo,$VarTwo] main.mac`

_Only tested with bash shell._

**Comment by djboersma** [comment]
I think you should just use double quotes. Within double quotes, shell variables are expanded. Also: you don't really need any whitespace between the alias definitions. So I usually do something like:

`Gate -a "[AliasOne,$varone][AliasTwo,$vartwo]" main.mac`

**Comment by TomThePhysicist** [comment]
Thanks, it work even without quotes. The space between aliases was causing the problem.
`Gate -a [AliasOne,$varone][AliasTwo,$vartwo] main.mac`
