### ISSUE TITLE
If there is  a Bug!

### ISSUE THREAD

**Issue by Muntasirqa** [OpenGATE/Gate#692]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.4, OS 11.3]
 - Gate version or commit hash: [e.g. v9.1, vGate, fa29532]
 - Geant4 version: [e.g. 10.7]
 - Root version: [e.g. v6-34-00]
 - compiler version: [e.g. clang 12.0.5, gcc 7.5.0]

**Minimal example**
*main.mac*:
```bash
```

**Expected behavior**

**Additional context**

**Comment by kochebina** [comment]
From the information provided, it is hard to understand the issue.
Could you, please, open another more specific issue on the problem.
