### ISSUE TITLE
questions in CT simulation

### ISSUE THREAD

**Issue by seanlammm** [OpenGATE/Gate#694]
Dear GATE users and developers,
       I am performing Gate simulations using GATE-9.2, and I have encountered two issues.

1. The first issue is related to the output of CT projection images. In my simulation, I tried not to define the source dose, but instead set the number of primary particles for each projection using /gate/application/setTotalNumberOfPrimaries (for example, rotating one degree per second, collecting data for 360 seconds). The .mac file runs by dividing the task into 360 subtasks and executing them on a cluster. According to my understanding, the output of the projection images should correspond to each subtask. However, based on the log files during execution, each subtask runs for 2 seconds. For example, subtask 1 should collect data for 0-1 seconds, but during the simulation run, it actually collected data for both 0-1 and 1-2 seconds, resulting in two projection images being output for subtask 1. I am unsure whether this is correct. 

2. The second issue is regarding the limitations of precision in GATE. Before performing the (voxelized) CT scan of the mouse phantom, I attempted to test the simulation setup using an air mouse phantom (all voxel materials were specified as air). The tests produced satisfactory results, so I proceeded with the normal material mouse phantom simulation (only changing the material file specified in the .mac file). However, during the normal material mouse phantom simulation, I encountered numerous warnings pointing to the same issue:

```
G4PenelopeComptonModel:
LowPoint: -1, High Point: 1
Tolerance: 1e-05
Calls: 20460, Integral: 0, Error: nan
Number of open subintervals: 512
WARNING: the required accuracy has not been attained
```

I tried using mouse phantoms with different voxel sizes, such as 0.1x0.1x0.1 mm, 0.58x0.58x0.58 mm, and 1x1x1 mm, but none of them could run successfully.

Thank you in advance, 

Sean

**Comment by kochebina** [comment]
Hello, 

Please, adress this kind of questions to Gate mailing list: opengate-l[at]in2p3.fr 

Kind regards,
Olga
