### ISSUE TITLE
installing vgate through wsl

### ISSUE THREAD

**Issue by santoshgate** [OpenGATE/Gate#702]
Hi

I am unable to install vgate in unbunto through wsl
I have wsl and unbunto 22 .04 in my PC
please guide me how to install vgate and run Vgate
Thanking you

**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 18.4, OS 11.3]
 - Gate version or commit hash: [e.g. v9.1, vGate, fa29532]
 - Geant4 version: [e.g. 10.7]
 - Root version: [e.g. v6-34-00]
 - compiler version: [e.g. clang 12.0.5, gcc 7.5.0]

**Minimal example**
*main.mac*:
```bash
```

**Expected behavior**

**Additional context**

**Comment by kochebina** [comment]
Hello, 

Please, adress this kind of questions to Gate mailing list: opengate-l[at]in2p3.fr 

Kind regards,
Olga
