### ISSUE TITLE
FastY90 positron spectrum issue

### ISSUE THREAD

**Issue by canonnervio** [OpenGATE/Gate#80]
I compiled the latest Gate/develop (3b8fafba8c470d55b952f4519e3acb8e755182f7) but I cannot replicate the positron kinetic energy spectrum output, see below.

The positron kinetic energy is exactly the same as the brem spectrum, also confirmed in the root output files directly, the error does not come from the plotting.

The code was added in #71 by @JStrydhorst.

![fasty90_output](https://cloud.githubusercontent.com/assets/4517510/16760025/3519bd72-481a-11e6-9f9f-460597f3ee9c.png)

My system:
Ubuntu 16.04 LTS
Geant4.10.02.p02
Root 5.34.36
Gate 7.2 develop (3b8fafba8c470d55b952f4519e3acb8e755182f7), no GPU, no cluster

Thanks for any hints regarding the cause of this!

**Comment by JStrydhorst** [comment]
I suspect the problem is in the analysis? How are you extracting the energy spectra? Are you using an actor that filters on primary particles generated? That you have an identical number of entries in both spectra is suspicious. At the very least, there should be far fewer positrons (~32 per million decays) than brem photons (~6 % of the number of decays).

**Comment by canonnervio** [comment]
I'm using the code you provided in [plot.C](https://github.com/OpenGATE/Gate/blob/develop/examples/example_fastY90/output/plot.C):

```
...
// open the output file 
TFile* f2 =new TFile (" fastY90Pos.root"); 
// and print the content
f2->ls();

// retrieve the energy spectrum histogram 
TH1F * h2 = (TH1F*)f2->Get("energySpectrum");
h2->SetLineColor(kRed);
// set title and the axis legend
h2->SetTitle("fastY90 positron kinetic energy");
h2->GetXaxis()->SetTitle("Energy (MeV)");
h2->GetYaxis()->SetTitle("Counts");
h2->GetXaxis()->SetRangeUser(0. ,1);

// statistic type ( (1) write mean value, number of entries and RMS)
h2->SetStats(1);

// draw histogram using point (P) associated with error bar (E) or HIST for histogramm
c1->cd(2);
h2->Draw("HIST");
...
```

and the output was generated with the unmodified [output.mac](https://github.com/OpenGATE/Gate/blob/develop/examples/example_fastY90/mac/output.mac):

```
...
/gate/actor/addActor EnergySpectrumActor pos_actor
/gate/actor/pos_actor/attachTo MainBox
/gate/actor/pos_actor/addFilter    particleFilter
/gate/actor/pos_actor/particleFilter/addParticle  e+
/gate/actor/pos_actor/save output/fastY90Pos.root
/gate/actor/pos_actor/energySpectrum/setEmin 0 eV
/gate/actor/pos_actor/energySpectrum/setEmax 1 MeV
/gate/actor/pos_actor/energySpectrum/setNumberOfBins 100
```

I agree with your point on the suspicious numbers of particles being exactly the same. Even inspecting the fastY90Pos.root file directly yields the duplicate data:
![fasty90pos_root](https://cloud.githubusercontent.com/assets/4517510/16765457/754ac908-4834-11e6-8ad7-e8019a561cb7.PNG)

**Comment by JStrydhorst** [comment]
I really don't understand. I created the example plot using the code that's in the example directory, and rereading, everything appears to be in order.

One thing I do notice is that the total number of entries in your output (6504827) is exactly equal to the sum of the brem and positron entries (6501704 and 3123 respectively) that I got when I created the example. It seems like the particle filter of the actor is doing nothing and both of your outputs contain both the gammas and the positrons. The number of positrons is small, so the peak isn't visible in the plot.

**Comment by dsarrut** [comment]
Hello, 
any progress on that issue ? Should we still consider it as open ?

**Comment by canonnervio** [comment]
I tried to reproduce this behavior on multiple machines with the same configuration (Ubuntu 16.04 LTS, Geant4.10.02.p02, Root 5.34.36) and I could not get the plots provided, i.e. the correct positron kinetic energy. Maybe someone else can try and confirm this issue?

**Comment by canonnervio** [comment]
I re-evaluated this issue with Gate 8.0, Geant4 10.3.1 and root 6.10/00 and I cannot reproduce it any more.
With the versions mentioned it works as intended. I consider this issue closed.
