### ISSUE TITLE
Creation of ParameterisedCollimator

### ISSUE THREAD

**Issue by martijn-d** [OpenGATE/Gate#93]
The creation of a ParameterisedCollimator:

```
/gate/geometry/setMaterialDatabase GateMaterials.db

/gate/world/geometry/setXLength 100 cm
/gate/world/geometry/setYLength 100 cm
/gate/world/geometry/setZLength 100 cm

/gate/world/daughters/name coll
/gate/world/daughters/insert collimator
/gate/coll/geometry/setDimensionX 20. cm
/gate/coll/geometry/setDimensionY 20. cm
/gate/coll/geometry/setFocalDistanceX 60. cm
/gate/coll/geometry/setFocalDistanceY 0. cm
/gate/coll/geometry/setHeight 4. cm
/gate/coll/geometry/setSeptalThickness 0.1 cm
/gate/coll/geometry/setInnerRadius 0.05 cm
/gate/coll/setMaterial Lead
/gate/coll/vis/setColor red
/gate/coll/vis/forceWireframe

/vis/open OGL
/vis/drawVolume  

/gate/run/initialize 
```

results in the following error:

`GateVVolume.cc (l.189): The material of the volume hole is not defined.`

This problem has been found before:
[http://thread.gmane.org/gmane.comp.science.opengate.user/5039](http://thread.gmane.org/gmane.comp.science.opengate.user/5039)

**Comment by martijn-d** [comment]
Fixed by adding:
`SetMaterialName(itsMaterialName);`
in
`/source/geometry/src/GateParameterisedHole.cc`

**Comment by brenthuisman** [comment]
Which line? You can submit a pull request or let me know which line, then I can add it.

**Comment by martijn-d** [comment]
Line 27.
