### ISSUE TITLE
Gjs parsing issue with multiple, same aliases per line

### ISSUE THREAD

**Issue by canonnervio** [OpenGATE/Gate#94]
Apparantly gjs has an issue parsing the same alias more than once per line, e.g. a command like 

`/gate/SPECThead/placement/setTranslation       {transl} {transl} 0 mm`

with the parameter 'transl' e.g. '5' passed to it is parsed to 

`/gate/SPECThead/placement/setTranslation       5 {transl} 0 mm`

instead of

`/gate/SPECThead/placement/setTranslation       5 5 0 mm`

**Comment by djboersma** [comment]
Hi @canonnervio, could you try replacing `if` by `while` in line 224 of `cluster_tools/jobsplitter/src/GateMacfileParser.cc`? If that solves the problem: could you submit a pull request with it? :)
