### ISSUE TITLE
Incorrect LYSO Density

### ISSUE THREAD

**Issue by dfreese** [OpenGATE/Gate#99]
Not sure if this has been brought up before, but the density for LYSO in the materials database has a listed density of 5.37 g/cm3, but it should be 7.4g/cm3, like LSO.

**Comment by dfreese** [comment]
Sorry, close to LSO, at 7.11g/cm3 as per L. Pidol et al., "[High efficiency of lutetium silicate scintillators, Ce-doped LPS, and LYSO crystals](http://dx.doi.org/10.1109/TNS.2004.829542)," in IEEE Transactions on Nuclear Science, vol. 51, no. 3, pp. 1084-1087, June 2004.

**Comment by mchamberland** [comment]
Yes, this has been discussed on the mailing list before. The problem is that there is no "one" correct density for LYSO. Please see [Michaela's post](http://webcache.googleusercontent.com/search?q=cache:sBGonaUqhOIJ:permalink.gmane.org/gmane.comp.science.opengate.user/3420+&cd=1&hl=en&ct=clnk&gl=ca). I'm not sure how the Gate developers should handle this...

**Comment by patayg** [comment]
Indeed, LYSO density varies from vendor to vendor. However, not all users are aware of such subtleties, so a "not so bad" value should be provided (e.g. 7.3 g/cm3 or something similar is still better than the current 5.37).

**Comment by mchamberland** [comment]
Yes, I agree. Hopefully, someone on the Gate team also agrees!

**Comment by dfreese** [comment]
@mchamberland and @patayg thanks for clarifying that.  Hopefully it can be changed to something generically useful.  People who know their exact crystal specs are going to change it anyway.

**Comment by dsarrut** [comment]
Hello, 
what do you suggest ? Could you provide a "not so bad" replacement for the current values ? 
thanks

**Comment by dfreese** [comment]
I would suggest anything between the reference I posted previously at 7.11g/cm3, and the 7.3g/cm3 @mchamberland mentioned from the [mailing list post](http://article.gmane.org/gmane.comp.science.opengate.user/3420).  (The previous google cache link was dead)

I haven't seen any values in literature quoted outside of this range, though I'm always happy to be proven wrong.  My preference would be to chose a value with a valid reference in literature, so I would suggest 7.11g/cm3, but I there are perhaps other references that could be cited.

**Comment by dsarrut** [comment]
Done : commit 70c112c676ba4be345a8a5945d5a64d2ce7cfba2

**Comment by dfreese** [comment]
I noticed commit 18d42d1 reverted this change.  Was that intentional?  It doesn't seem related to the [PR](https://github.com/OpenGATE/Gate/pull/132).

**Comment by dsarrut** [comment]
Revert the reversion  ... (don't know why it was reverted) e4ef6b551b204e7f25ba62e1f50718707ec4d1b0 fda5f9f347723d98ea7e236068e59204e9f7bf39

**Comment by MarieleStockhoff** [comment]
The LYSO in the main database is updated but the incorrect definitions are still hiding in the .db in the examples.

**Comment by dfreese** [comment]
I'm not super familiar with the GATE development process, but it looks like those files are there from whenever the benchmarks were run after a breaking change.

- [benchImageNavigators/pet](https://github.com/OpenGATE/Gate/blob/071dd73d910f3ddb6eb1c2beb56c79a41bed764c/benchmarks/benchImageNavigators/pet/data/GateMaterials.db)
- [benchImageNavigators/rt](https://github.com/OpenGATE/Gate/blob/071dd73d910f3ddb6eb1c2beb56c79a41bed764c/benchmarks/benchImageNavigators/rt/data/GateMaterials.db)
- [benchImaging](https://github.com/OpenGATE/Gate/blob/071dd73d910f3ddb6eb1c2beb56c79a41bed764c/benchmarks/benchImaging/data/GateMaterials.db)
- [benchRT](https://github.com/OpenGATE/Gate/blob/071dd73d910f3ddb6eb1c2beb56c79a41bed764c/benchmarks/benchRT/data/GateMaterials.db)
- [benchParticleFilter](https://github.com/OpenGATE/Gate/blob/49a302da109cb2f157e34fdc6413cfd854af0cb1/benchmarks/benchParticleFilter/data/GateMaterials.db)


Have you noticed a situation where these have caused confusion?  If so, perhaps a readme could be added to those data folders cautioning against that, or something similar.
